// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public interface GetAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.profile.GetAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot slots = 1;</code>
   */
  java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot> 
      getSlotsList();
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot slots = 1;</code>
   */
  com.hiresphere.profile.grpc.AvailabilitySlot getSlots(int index);
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot slots = 1;</code>
   */
  int getSlotsCount();
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot slots = 1;</code>
   */
  java.util.List<? extends com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder> 
      getSlotsOrBuilderList();
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot slots = 1;</code>
   */
  com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder getSlotsOrBuilder(
      int index);
}
