// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * Protobuf type {@code com.hiresphere.profile.GetProfileResponse}
 */
public final class GetProfileResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.profile.GetProfileResponse)
    GetProfileResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProfileResponse.newBuilder() to construct.
  private GetProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProfileResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProfileResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_GetProfileResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_GetProfileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.profile.grpc.GetProfileResponse.class, com.hiresphere.profile.grpc.GetProfileResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROFILE_FIELD_NUMBER = 1;
  private com.hiresphere.profile.grpc.Profile profile_;
  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   * @return Whether the profile field is set.
   */
  @java.lang.Override
  public boolean hasProfile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   * @return The profile.
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.Profile getProfile() {
    return profile_ == null ? com.hiresphere.profile.grpc.Profile.getDefaultInstance() : profile_;
  }
  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.ProfileOrBuilder getProfileOrBuilder() {
    return profile_ == null ? com.hiresphere.profile.grpc.Profile.getDefaultInstance() : profile_;
  }

  public static final int FOUND_FIELD_NUMBER = 2;
  private boolean found_ = false;
  /**
   * <code>bool found = 2;</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getProfile());
    }
    if (found_ != false) {
      output.writeBool(2, found_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProfile());
    }
    if (found_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, found_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.profile.grpc.GetProfileResponse)) {
      return super.equals(obj);
    }
    com.hiresphere.profile.grpc.GetProfileResponse other = (com.hiresphere.profile.grpc.GetProfileResponse) obj;

    if (hasProfile() != other.hasProfile()) return false;
    if (hasProfile()) {
      if (!getProfile()
          .equals(other.getProfile())) return false;
    }
    if (getFound()
        != other.getFound()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProfile()) {
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getProfile().hashCode();
    }
    hash = (37 * hash) + FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFound());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.profile.grpc.GetProfileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.profile.grpc.GetProfileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.GetProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.profile.grpc.GetProfileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hiresphere.profile.GetProfileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.profile.GetProfileResponse)
      com.hiresphere.profile.grpc.GetProfileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_GetProfileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_GetProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.profile.grpc.GetProfileResponse.class, com.hiresphere.profile.grpc.GetProfileResponse.Builder.class);
    }

    // Construct using com.hiresphere.profile.grpc.GetProfileResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProfileFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      found_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_GetProfileResponse_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.GetProfileResponse getDefaultInstanceForType() {
      return com.hiresphere.profile.grpc.GetProfileResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.GetProfileResponse build() {
      com.hiresphere.profile.grpc.GetProfileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.GetProfileResponse buildPartial() {
      com.hiresphere.profile.grpc.GetProfileResponse result = new com.hiresphere.profile.grpc.GetProfileResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hiresphere.profile.grpc.GetProfileResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.profile_ = profileBuilder_ == null
            ? profile_
            : profileBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.found_ = found_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.profile.grpc.GetProfileResponse) {
        return mergeFrom((com.hiresphere.profile.grpc.GetProfileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.profile.grpc.GetProfileResponse other) {
      if (other == com.hiresphere.profile.grpc.GetProfileResponse.getDefaultInstance()) return this;
      if (other.hasProfile()) {
        mergeProfile(other.getProfile());
      }
      if (other.getFound() != false) {
        setFound(other.getFound());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getProfileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              found_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.hiresphere.profile.grpc.Profile profile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder> profileBuilder_;
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     * @return Whether the profile field is set.
     */
    public boolean hasProfile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     * @return The profile.
     */
    public com.hiresphere.profile.grpc.Profile getProfile() {
      if (profileBuilder_ == null) {
        return profile_ == null ? com.hiresphere.profile.grpc.Profile.getDefaultInstance() : profile_;
      } else {
        return profileBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public Builder setProfile(com.hiresphere.profile.grpc.Profile value) {
      if (profileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profile_ = value;
      } else {
        profileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public Builder setProfile(
        com.hiresphere.profile.grpc.Profile.Builder builderForValue) {
      if (profileBuilder_ == null) {
        profile_ = builderForValue.build();
      } else {
        profileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public Builder mergeProfile(com.hiresphere.profile.grpc.Profile value) {
      if (profileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          profile_ != null &&
          profile_ != com.hiresphere.profile.grpc.Profile.getDefaultInstance()) {
          getProfileBuilder().mergeFrom(value);
        } else {
          profile_ = value;
        }
      } else {
        profileBuilder_.mergeFrom(value);
      }
      if (profile_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public Builder clearProfile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public com.hiresphere.profile.grpc.Profile.Builder getProfileBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProfileFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    public com.hiresphere.profile.grpc.ProfileOrBuilder getProfileOrBuilder() {
      if (profileBuilder_ != null) {
        return profileBuilder_.getMessageOrBuilder();
      } else {
        return profile_ == null ?
            com.hiresphere.profile.grpc.Profile.getDefaultInstance() : profile_;
      }
    }
    /**
     * <code>.com.hiresphere.profile.Profile profile = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder> 
        getProfileFieldBuilder() {
      if (profileBuilder_ == null) {
        profileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder>(
                getProfile(),
                getParentForChildren(),
                isClean());
        profile_ = null;
      }
      return profileBuilder_;
    }

    private boolean found_ ;
    /**
     * <code>bool found = 2;</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return found_;
    }
    /**
     * <code>bool found = 2;</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {

      found_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool found = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      found_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.profile.GetProfileResponse)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.profile.GetProfileResponse)
  private static final com.hiresphere.profile.grpc.GetProfileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.profile.grpc.GetProfileResponse();
  }

  public static com.hiresphere.profile.grpc.GetProfileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProfileResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetProfileResponse>() {
    @java.lang.Override
    public GetProfileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetProfileResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProfileResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.profile.grpc.GetProfileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

