// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * Protobuf enum {@code com.hiresphere.profile.InterviewType}
 */
public enum InterviewType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SYSTEM_DESIGN = 0;</code>
   */
  SYSTEM_DESIGN(0),
  /**
   * <code>DATA_STRUCTURES = 1;</code>
   */
  DATA_STRUCTURES(1),
  /**
   * <code>BEHAVIORAL = 2;</code>
   */
  BEHAVIORAL(2),
  /**
   * <code>FRONTEND = 3;</code>
   */
  FRONTEND(3),
  /**
   * <code>BACKEND = 4;</code>
   */
  BACKEND(4),
  /**
   * <code>FULLSTACK = 5;</code>
   */
  FULLSTACK(5),
  /**
   * <code>DEVOPS = 6;</code>
   */
  DEVOPS(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SYSTEM_DESIGN = 0;</code>
   */
  public static final int SYSTEM_DESIGN_VALUE = 0;
  /**
   * <code>DATA_STRUCTURES = 1;</code>
   */
  public static final int DATA_STRUCTURES_VALUE = 1;
  /**
   * <code>BEHAVIORAL = 2;</code>
   */
  public static final int BEHAVIORAL_VALUE = 2;
  /**
   * <code>FRONTEND = 3;</code>
   */
  public static final int FRONTEND_VALUE = 3;
  /**
   * <code>BACKEND = 4;</code>
   */
  public static final int BACKEND_VALUE = 4;
  /**
   * <code>FULLSTACK = 5;</code>
   */
  public static final int FULLSTACK_VALUE = 5;
  /**
   * <code>DEVOPS = 6;</code>
   */
  public static final int DEVOPS_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InterviewType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static InterviewType forNumber(int value) {
    switch (value) {
      case 0: return SYSTEM_DESIGN;
      case 1: return DATA_STRUCTURES;
      case 2: return BEHAVIORAL;
      case 3: return FRONTEND;
      case 4: return BACKEND;
      case 5: return FULLSTACK;
      case 6: return DEVOPS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InterviewType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InterviewType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InterviewType>() {
          public InterviewType findValueByNumber(int number) {
            return InterviewType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final InterviewType[] VALUES = values();

  public static InterviewType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private InterviewType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.hiresphere.profile.InterviewType)
}

