// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * <pre>
 * ─── ENUMS ────────────────────────────────────────────────────────────────────
 * </pre>
 *
 * Protobuf enum {@code com.hiresphere.profile.ProfileType}
 */
public enum ProfileType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CANDIDATE = 0;</code>
   */
  CANDIDATE(0),
  /**
   * <code>INTERVIEWER = 1;</code>
   */
  INTERVIEWER(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CANDIDATE = 0;</code>
   */
  public static final int CANDIDATE_VALUE = 0;
  /**
   * <code>INTERVIEWER = 1;</code>
   */
  public static final int INTERVIEWER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProfileType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProfileType forNumber(int value) {
    switch (value) {
      case 0: return CANDIDATE;
      case 1: return INTERVIEWER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProfileType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProfileType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProfileType>() {
          public ProfileType findValueByNumber(int number) {
            return ProfileType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ProfileType[] VALUES = values();

  public static ProfileType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProfileType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.hiresphere.profile.ProfileType)
}

