// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * <pre>
 * ─── MESSAGES ─────────────────────────────────────────────────────────────────
 * </pre>
 *
 * Protobuf type {@code com.hiresphere.profile.Profile}
 */
public final class Profile extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.profile.Profile)
    ProfileOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Profile.newBuilder() to construct.
  private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Profile() {
    userId_ = "";
    name_ = "";
    email_ = "";
    profileType_ = 0;
    bio_ = "";
    domains_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    badges_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    interviewTypes_ = java.util.Collections.emptyList();
    availability_ = java.util.Collections.emptyList();
    avatarUrl_ = "";
    linkedinUrl_ = "";
    githubUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Profile();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_Profile_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_Profile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.profile.grpc.Profile.class, com.hiresphere.profile.grpc.Profile.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFILE_TYPE_FIELD_NUMBER = 4;
  private int profileType_ = 0;
  /**
   * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
   * @return The enum numeric value on the wire for profileType.
   */
  @java.lang.Override public int getProfileTypeValue() {
    return profileType_;
  }
  /**
   * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
   * @return The profileType.
   */
  @java.lang.Override public com.hiresphere.profile.grpc.ProfileType getProfileType() {
    com.hiresphere.profile.grpc.ProfileType result = com.hiresphere.profile.grpc.ProfileType.forNumber(profileType_);
    return result == null ? com.hiresphere.profile.grpc.ProfileType.UNRECOGNIZED : result;
  }

  public static final int BIO_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bio_ = "";
  /**
   * <code>string bio = 5;</code>
   * @return The bio.
   */
  @java.lang.Override
  public java.lang.String getBio() {
    java.lang.Object ref = bio_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bio_ = s;
      return s;
    }
  }
  /**
   * <code>string bio = 5;</code>
   * @return The bytes for bio.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBioBytes() {
    java.lang.Object ref = bio_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bio_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAINS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList domains_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string domains = 6;</code>
   * @return A list containing the domains.
   */
  public com.google.protobuf.ProtocolStringList
      getDomainsList() {
    return domains_;
  }
  /**
   * <code>repeated string domains = 6;</code>
   * @return The count of domains.
   */
  public int getDomainsCount() {
    return domains_.size();
  }
  /**
   * <code>repeated string domains = 6;</code>
   * @param index The index of the element to return.
   * @return The domains at the given index.
   */
  public java.lang.String getDomains(int index) {
    return domains_.get(index);
  }
  /**
   * <code>repeated string domains = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the domains at the given index.
   */
  public com.google.protobuf.ByteString
      getDomainsBytes(int index) {
    return domains_.getByteString(index);
  }

  public static final int BADGES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList badges_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string badges = 7;</code>
   * @return A list containing the badges.
   */
  public com.google.protobuf.ProtocolStringList
      getBadgesList() {
    return badges_;
  }
  /**
   * <code>repeated string badges = 7;</code>
   * @return The count of badges.
   */
  public int getBadgesCount() {
    return badges_.size();
  }
  /**
   * <code>repeated string badges = 7;</code>
   * @param index The index of the element to return.
   * @return The badges at the given index.
   */
  public java.lang.String getBadges(int index) {
    return badges_.get(index);
  }
  /**
   * <code>repeated string badges = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the badges at the given index.
   */
  public com.google.protobuf.ByteString
      getBadgesBytes(int index) {
    return badges_.getByteString(index);
  }

  public static final int RATING_FIELD_NUMBER = 8;
  private float rating_ = 0F;
  /**
   * <code>float rating = 8;</code>
   * @return The rating.
   */
  @java.lang.Override
  public float getRating() {
    return rating_;
  }

  public static final int TOTAL_REVIEWS_FIELD_NUMBER = 9;
  private int totalReviews_ = 0;
  /**
   * <code>int32 total_reviews = 9;</code>
   * @return The totalReviews.
   */
  @java.lang.Override
  public int getTotalReviews() {
    return totalReviews_;
  }

  public static final int YEARS_EXPERIENCE_FIELD_NUMBER = 10;
  private int yearsExperience_ = 0;
  /**
   * <code>int32 years_experience = 10;</code>
   * @return The yearsExperience.
   */
  @java.lang.Override
  public int getYearsExperience() {
    return yearsExperience_;
  }

  public static final int INTERVIEW_TYPES_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private java.util.List<java.lang.Integer> interviewTypes_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.hiresphere.profile.grpc.InterviewType> interviewTypes_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.hiresphere.profile.grpc.InterviewType>() {
            public com.hiresphere.profile.grpc.InterviewType convert(java.lang.Integer from) {
              com.hiresphere.profile.grpc.InterviewType result = com.hiresphere.profile.grpc.InterviewType.forNumber(from);
              return result == null ? com.hiresphere.profile.grpc.InterviewType.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
   * @return A list containing the interviewTypes.
   */
  @java.lang.Override
  public java.util.List<com.hiresphere.profile.grpc.InterviewType> getInterviewTypesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.hiresphere.profile.grpc.InterviewType>(interviewTypes_, interviewTypes_converter_);
  }
  /**
   * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
   * @return The count of interviewTypes.
   */
  @java.lang.Override
  public int getInterviewTypesCount() {
    return interviewTypes_.size();
  }
  /**
   * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
   * @param index The index of the element to return.
   * @return The interviewTypes at the given index.
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.InterviewType getInterviewTypes(int index) {
    return interviewTypes_converter_.convert(interviewTypes_.get(index));
  }
  /**
   * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
   * @return A list containing the enum numeric values on the wire for interviewTypes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getInterviewTypesValueList() {
    return interviewTypes_;
  }
  /**
   * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of interviewTypes at the given index.
   */
  @java.lang.Override
  public int getInterviewTypesValue(int index) {
    return interviewTypes_.get(index);
  }
  private int interviewTypesMemoizedSerializedSize;

  public static final int AVAILABILITY_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot> availability_;
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
   */
  @java.lang.Override
  public java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot> getAvailabilityList() {
    return availability_;
  }
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder> 
      getAvailabilityOrBuilderList() {
    return availability_;
  }
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
   */
  @java.lang.Override
  public int getAvailabilityCount() {
    return availability_.size();
  }
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.AvailabilitySlot getAvailability(int index) {
    return availability_.get(index);
  }
  /**
   * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder getAvailabilityOrBuilder(
      int index) {
    return availability_.get(index);
  }

  public static final int AVATAR_URL_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object avatarUrl_ = "";
  /**
   * <code>string avatar_url = 13;</code>
   * @return The avatarUrl.
   */
  @java.lang.Override
  public java.lang.String getAvatarUrl() {
    java.lang.Object ref = avatarUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatarUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar_url = 13;</code>
   * @return The bytes for avatarUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvatarUrlBytes() {
    java.lang.Object ref = avatarUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatarUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_PER_HOUR_FIELD_NUMBER = 14;
  private int pricePerHour_ = 0;
  /**
   * <code>int32 price_per_hour = 14;</code>
   * @return The pricePerHour.
   */
  @java.lang.Override
  public int getPricePerHour() {
    return pricePerHour_;
  }

  public static final int LINKEDIN_URL_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object linkedinUrl_ = "";
  /**
   * <code>string linkedin_url = 15;</code>
   * @return The linkedinUrl.
   */
  @java.lang.Override
  public java.lang.String getLinkedinUrl() {
    java.lang.Object ref = linkedinUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      linkedinUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string linkedin_url = 15;</code>
   * @return The bytes for linkedinUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLinkedinUrlBytes() {
    java.lang.Object ref = linkedinUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      linkedinUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GITHUB_URL_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object githubUrl_ = "";
  /**
   * <code>string github_url = 16;</code>
   * @return The githubUrl.
   */
  @java.lang.Override
  public java.lang.String getGithubUrl() {
    java.lang.Object ref = githubUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      githubUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string github_url = 16;</code>
   * @return The bytes for githubUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGithubUrlBytes() {
    java.lang.Object ref = githubUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      githubUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 17;
  private long createdAt_ = 0L;
  /**
   * <code>int64 created_at = 17;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 18;
  private long updatedAt_ = 0L;
  /**
   * <code>int64 updated_at = 18;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (profileType_ != com.hiresphere.profile.grpc.ProfileType.CANDIDATE.getNumber()) {
      output.writeEnum(4, profileType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bio_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, bio_);
    }
    for (int i = 0; i < domains_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, domains_.getRaw(i));
    }
    for (int i = 0; i < badges_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, badges_.getRaw(i));
    }
    if (java.lang.Float.floatToRawIntBits(rating_) != 0) {
      output.writeFloat(8, rating_);
    }
    if (totalReviews_ != 0) {
      output.writeInt32(9, totalReviews_);
    }
    if (yearsExperience_ != 0) {
      output.writeInt32(10, yearsExperience_);
    }
    if (getInterviewTypesList().size() > 0) {
      output.writeUInt32NoTag(90);
      output.writeUInt32NoTag(interviewTypesMemoizedSerializedSize);
    }
    for (int i = 0; i < interviewTypes_.size(); i++) {
      output.writeEnumNoTag(interviewTypes_.get(i));
    }
    for (int i = 0; i < availability_.size(); i++) {
      output.writeMessage(12, availability_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatarUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, avatarUrl_);
    }
    if (pricePerHour_ != 0) {
      output.writeInt32(14, pricePerHour_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(linkedinUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, linkedinUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(githubUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, githubUrl_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(17, createdAt_);
    }
    if (updatedAt_ != 0L) {
      output.writeInt64(18, updatedAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (profileType_ != com.hiresphere.profile.grpc.ProfileType.CANDIDATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, profileType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bio_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, bio_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < domains_.size(); i++) {
        dataSize += computeStringSizeNoTag(domains_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDomainsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < badges_.size(); i++) {
        dataSize += computeStringSizeNoTag(badges_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getBadgesList().size();
    }
    if (java.lang.Float.floatToRawIntBits(rating_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, rating_);
    }
    if (totalReviews_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, totalReviews_);
    }
    if (yearsExperience_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, yearsExperience_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < interviewTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(interviewTypes_.get(i));
      }
      size += dataSize;
      if (!getInterviewTypesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }interviewTypesMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < availability_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, availability_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatarUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, avatarUrl_);
    }
    if (pricePerHour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, pricePerHour_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(linkedinUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, linkedinUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(githubUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, githubUrl_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(17, createdAt_);
    }
    if (updatedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(18, updatedAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.profile.grpc.Profile)) {
      return super.equals(obj);
    }
    com.hiresphere.profile.grpc.Profile other = (com.hiresphere.profile.grpc.Profile) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (profileType_ != other.profileType_) return false;
    if (!getBio()
        .equals(other.getBio())) return false;
    if (!getDomainsList()
        .equals(other.getDomainsList())) return false;
    if (!getBadgesList()
        .equals(other.getBadgesList())) return false;
    if (java.lang.Float.floatToIntBits(getRating())
        != java.lang.Float.floatToIntBits(
            other.getRating())) return false;
    if (getTotalReviews()
        != other.getTotalReviews()) return false;
    if (getYearsExperience()
        != other.getYearsExperience()) return false;
    if (!interviewTypes_.equals(other.interviewTypes_)) return false;
    if (!getAvailabilityList()
        .equals(other.getAvailabilityList())) return false;
    if (!getAvatarUrl()
        .equals(other.getAvatarUrl())) return false;
    if (getPricePerHour()
        != other.getPricePerHour()) return false;
    if (!getLinkedinUrl()
        .equals(other.getLinkedinUrl())) return false;
    if (!getGithubUrl()
        .equals(other.getGithubUrl())) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (getUpdatedAt()
        != other.getUpdatedAt()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PROFILE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + profileType_;
    hash = (37 * hash) + BIO_FIELD_NUMBER;
    hash = (53 * hash) + getBio().hashCode();
    if (getDomainsCount() > 0) {
      hash = (37 * hash) + DOMAINS_FIELD_NUMBER;
      hash = (53 * hash) + getDomainsList().hashCode();
    }
    if (getBadgesCount() > 0) {
      hash = (37 * hash) + BADGES_FIELD_NUMBER;
      hash = (53 * hash) + getBadgesList().hashCode();
    }
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRating());
    hash = (37 * hash) + TOTAL_REVIEWS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalReviews();
    hash = (37 * hash) + YEARS_EXPERIENCE_FIELD_NUMBER;
    hash = (53 * hash) + getYearsExperience();
    if (getInterviewTypesCount() > 0) {
      hash = (37 * hash) + INTERVIEW_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + interviewTypes_.hashCode();
    }
    if (getAvailabilityCount() > 0) {
      hash = (37 * hash) + AVAILABILITY_FIELD_NUMBER;
      hash = (53 * hash) + getAvailabilityList().hashCode();
    }
    hash = (37 * hash) + AVATAR_URL_FIELD_NUMBER;
    hash = (53 * hash) + getAvatarUrl().hashCode();
    hash = (37 * hash) + PRICE_PER_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + getPricePerHour();
    hash = (37 * hash) + LINKEDIN_URL_FIELD_NUMBER;
    hash = (53 * hash) + getLinkedinUrl().hashCode();
    hash = (37 * hash) + GITHUB_URL_FIELD_NUMBER;
    hash = (53 * hash) + getGithubUrl().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdatedAt());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.profile.grpc.Profile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.profile.grpc.Profile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.profile.grpc.Profile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.Profile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.profile.grpc.Profile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ─── MESSAGES ─────────────────────────────────────────────────────────────────
   * </pre>
   *
   * Protobuf type {@code com.hiresphere.profile.Profile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.profile.Profile)
      com.hiresphere.profile.grpc.ProfileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_Profile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.profile.grpc.Profile.class, com.hiresphere.profile.grpc.Profile.Builder.class);
    }

    // Construct using com.hiresphere.profile.grpc.Profile.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      name_ = "";
      email_ = "";
      profileType_ = 0;
      bio_ = "";
      domains_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      badges_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      rating_ = 0F;
      totalReviews_ = 0;
      yearsExperience_ = 0;
      interviewTypes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      if (availabilityBuilder_ == null) {
        availability_ = java.util.Collections.emptyList();
      } else {
        availability_ = null;
        availabilityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      avatarUrl_ = "";
      pricePerHour_ = 0;
      linkedinUrl_ = "";
      githubUrl_ = "";
      createdAt_ = 0L;
      updatedAt_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_Profile_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.Profile getDefaultInstanceForType() {
      return com.hiresphere.profile.grpc.Profile.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.Profile build() {
      com.hiresphere.profile.grpc.Profile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.Profile buildPartial() {
      com.hiresphere.profile.grpc.Profile result = new com.hiresphere.profile.grpc.Profile(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.hiresphere.profile.grpc.Profile result) {
      if (((bitField0_ & 0x00000400) != 0)) {
        interviewTypes_ = java.util.Collections.unmodifiableList(interviewTypes_);
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.interviewTypes_ = interviewTypes_;
      if (availabilityBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0)) {
          availability_ = java.util.Collections.unmodifiableList(availability_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.availability_ = availability_;
      } else {
        result.availability_ = availabilityBuilder_.build();
      }
    }

    private void buildPartial0(com.hiresphere.profile.grpc.Profile result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.profileType_ = profileType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bio_ = bio_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        domains_.makeImmutable();
        result.domains_ = domains_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        badges_.makeImmutable();
        result.badges_ = badges_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.rating_ = rating_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.totalReviews_ = totalReviews_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.yearsExperience_ = yearsExperience_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.avatarUrl_ = avatarUrl_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.pricePerHour_ = pricePerHour_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.linkedinUrl_ = linkedinUrl_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.githubUrl_ = githubUrl_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.createdAt_ = createdAt_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.updatedAt_ = updatedAt_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.profile.grpc.Profile) {
        return mergeFrom((com.hiresphere.profile.grpc.Profile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.profile.grpc.Profile other) {
      if (other == com.hiresphere.profile.grpc.Profile.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.profileType_ != 0) {
        setProfileTypeValue(other.getProfileTypeValue());
      }
      if (!other.getBio().isEmpty()) {
        bio_ = other.bio_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.domains_.isEmpty()) {
        if (domains_.isEmpty()) {
          domains_ = other.domains_;
          bitField0_ |= 0x00000020;
        } else {
          ensureDomainsIsMutable();
          domains_.addAll(other.domains_);
        }
        onChanged();
      }
      if (!other.badges_.isEmpty()) {
        if (badges_.isEmpty()) {
          badges_ = other.badges_;
          bitField0_ |= 0x00000040;
        } else {
          ensureBadgesIsMutable();
          badges_.addAll(other.badges_);
        }
        onChanged();
      }
      if (other.getRating() != 0F) {
        setRating(other.getRating());
      }
      if (other.getTotalReviews() != 0) {
        setTotalReviews(other.getTotalReviews());
      }
      if (other.getYearsExperience() != 0) {
        setYearsExperience(other.getYearsExperience());
      }
      if (!other.interviewTypes_.isEmpty()) {
        if (interviewTypes_.isEmpty()) {
          interviewTypes_ = other.interviewTypes_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureInterviewTypesIsMutable();
          interviewTypes_.addAll(other.interviewTypes_);
        }
        onChanged();
      }
      if (availabilityBuilder_ == null) {
        if (!other.availability_.isEmpty()) {
          if (availability_.isEmpty()) {
            availability_ = other.availability_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureAvailabilityIsMutable();
            availability_.addAll(other.availability_);
          }
          onChanged();
        }
      } else {
        if (!other.availability_.isEmpty()) {
          if (availabilityBuilder_.isEmpty()) {
            availabilityBuilder_.dispose();
            availabilityBuilder_ = null;
            availability_ = other.availability_;
            bitField0_ = (bitField0_ & ~0x00000800);
            availabilityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAvailabilityFieldBuilder() : null;
          } else {
            availabilityBuilder_.addAllMessages(other.availability_);
          }
        }
      }
      if (!other.getAvatarUrl().isEmpty()) {
        avatarUrl_ = other.avatarUrl_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getPricePerHour() != 0) {
        setPricePerHour(other.getPricePerHour());
      }
      if (!other.getLinkedinUrl().isEmpty()) {
        linkedinUrl_ = other.linkedinUrl_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (!other.getGithubUrl().isEmpty()) {
        githubUrl_ = other.githubUrl_;
        bitField0_ |= 0x00008000;
        onChanged();
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      if (other.getUpdatedAt() != 0L) {
        setUpdatedAt(other.getUpdatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              profileType_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              bio_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDomainsIsMutable();
              domains_.add(s);
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureBadgesIsMutable();
              badges_.add(s);
              break;
            } // case 58
            case 69: {
              rating_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 69
            case 72: {
              totalReviews_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              yearsExperience_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              int tmpRaw = input.readEnum();
              ensureInterviewTypesIsMutable();
              interviewTypes_.add(tmpRaw);
              break;
            } // case 88
            case 90: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureInterviewTypesIsMutable();
                interviewTypes_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 90
            case 98: {
              com.hiresphere.profile.grpc.AvailabilitySlot m =
                  input.readMessage(
                      com.hiresphere.profile.grpc.AvailabilitySlot.parser(),
                      extensionRegistry);
              if (availabilityBuilder_ == null) {
                ensureAvailabilityIsMutable();
                availability_.add(m);
              } else {
                availabilityBuilder_.addMessage(m);
              }
              break;
            } // case 98
            case 106: {
              avatarUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              pricePerHour_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              linkedinUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 130: {
              githubUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00008000;
              break;
            } // case 130
            case 136: {
              createdAt_ = input.readInt64();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 144: {
              updatedAt_ = input.readInt64();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int profileType_ = 0;
    /**
     * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
     * @return The enum numeric value on the wire for profileType.
     */
    @java.lang.Override public int getProfileTypeValue() {
      return profileType_;
    }
    /**
     * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
     * @param value The enum numeric value on the wire for profileType to set.
     * @return This builder for chaining.
     */
    public Builder setProfileTypeValue(int value) {
      profileType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
     * @return The profileType.
     */
    @java.lang.Override
    public com.hiresphere.profile.grpc.ProfileType getProfileType() {
      com.hiresphere.profile.grpc.ProfileType result = com.hiresphere.profile.grpc.ProfileType.forNumber(profileType_);
      return result == null ? com.hiresphere.profile.grpc.ProfileType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
     * @param value The profileType to set.
     * @return This builder for chaining.
     */
    public Builder setProfileType(com.hiresphere.profile.grpc.ProfileType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      profileType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.ProfileType profile_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfileType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      profileType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bio_ = "";
    /**
     * <code>string bio = 5;</code>
     * @return The bio.
     */
    public java.lang.String getBio() {
      java.lang.Object ref = bio_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bio_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bio = 5;</code>
     * @return The bytes for bio.
     */
    public com.google.protobuf.ByteString
        getBioBytes() {
      java.lang.Object ref = bio_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bio = 5;</code>
     * @param value The bio to set.
     * @return This builder for chaining.
     */
    public Builder setBio(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bio_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string bio = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBio() {
      bio_ = getDefaultInstance().getBio();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string bio = 5;</code>
     * @param value The bytes for bio to set.
     * @return This builder for chaining.
     */
    public Builder setBioBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bio_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList domains_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDomainsIsMutable() {
      if (!domains_.isModifiable()) {
        domains_ = new com.google.protobuf.LazyStringArrayList(domains_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @return A list containing the domains.
     */
    public com.google.protobuf.ProtocolStringList
        getDomainsList() {
      domains_.makeImmutable();
      return domains_;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @return The count of domains.
     */
    public int getDomainsCount() {
      return domains_.size();
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param index The index of the element to return.
     * @return The domains at the given index.
     */
    public java.lang.String getDomains(int index) {
      return domains_.get(index);
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the domains at the given index.
     */
    public com.google.protobuf.ByteString
        getDomainsBytes(int index) {
      return domains_.getByteString(index);
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param index The index to set the value at.
     * @param value The domains to set.
     * @return This builder for chaining.
     */
    public Builder setDomains(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDomainsIsMutable();
      domains_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param value The domains to add.
     * @return This builder for chaining.
     */
    public Builder addDomains(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDomainsIsMutable();
      domains_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param values The domains to add.
     * @return This builder for chaining.
     */
    public Builder addAllDomains(
        java.lang.Iterable<java.lang.String> values) {
      ensureDomainsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, domains_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomains() {
      domains_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains = 6;</code>
     * @param value The bytes of the domains to add.
     * @return This builder for chaining.
     */
    public Builder addDomainsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDomainsIsMutable();
      domains_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList badges_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureBadgesIsMutable() {
      if (!badges_.isModifiable()) {
        badges_ = new com.google.protobuf.LazyStringArrayList(badges_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @return A list containing the badges.
     */
    public com.google.protobuf.ProtocolStringList
        getBadgesList() {
      badges_.makeImmutable();
      return badges_;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @return The count of badges.
     */
    public int getBadgesCount() {
      return badges_.size();
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param index The index of the element to return.
     * @return The badges at the given index.
     */
    public java.lang.String getBadges(int index) {
      return badges_.get(index);
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the badges at the given index.
     */
    public com.google.protobuf.ByteString
        getBadgesBytes(int index) {
      return badges_.getByteString(index);
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param index The index to set the value at.
     * @param value The badges to set.
     * @return This builder for chaining.
     */
    public Builder setBadges(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBadgesIsMutable();
      badges_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param value The badges to add.
     * @return This builder for chaining.
     */
    public Builder addBadges(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBadgesIsMutable();
      badges_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param values The badges to add.
     * @return This builder for chaining.
     */
    public Builder addAllBadges(
        java.lang.Iterable<java.lang.String> values) {
      ensureBadgesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, badges_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBadges() {
      badges_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string badges = 7;</code>
     * @param value The bytes of the badges to add.
     * @return This builder for chaining.
     */
    public Builder addBadgesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureBadgesIsMutable();
      badges_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private float rating_ ;
    /**
     * <code>float rating = 8;</code>
     * @return The rating.
     */
    @java.lang.Override
    public float getRating() {
      return rating_;
    }
    /**
     * <code>float rating = 8;</code>
     * @param value The rating to set.
     * @return This builder for chaining.
     */
    public Builder setRating(float value) {

      rating_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>float rating = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRating() {
      bitField0_ = (bitField0_ & ~0x00000080);
      rating_ = 0F;
      onChanged();
      return this;
    }

    private int totalReviews_ ;
    /**
     * <code>int32 total_reviews = 9;</code>
     * @return The totalReviews.
     */
    @java.lang.Override
    public int getTotalReviews() {
      return totalReviews_;
    }
    /**
     * <code>int32 total_reviews = 9;</code>
     * @param value The totalReviews to set.
     * @return This builder for chaining.
     */
    public Builder setTotalReviews(int value) {

      totalReviews_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_reviews = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalReviews() {
      bitField0_ = (bitField0_ & ~0x00000100);
      totalReviews_ = 0;
      onChanged();
      return this;
    }

    private int yearsExperience_ ;
    /**
     * <code>int32 years_experience = 10;</code>
     * @return The yearsExperience.
     */
    @java.lang.Override
    public int getYearsExperience() {
      return yearsExperience_;
    }
    /**
     * <code>int32 years_experience = 10;</code>
     * @param value The yearsExperience to set.
     * @return This builder for chaining.
     */
    public Builder setYearsExperience(int value) {

      yearsExperience_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 years_experience = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearYearsExperience() {
      bitField0_ = (bitField0_ & ~0x00000200);
      yearsExperience_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> interviewTypes_ =
      java.util.Collections.emptyList();
    private void ensureInterviewTypesIsMutable() {
      if (!((bitField0_ & 0x00000400) != 0)) {
        interviewTypes_ = new java.util.ArrayList<java.lang.Integer>(interviewTypes_);
        bitField0_ |= 0x00000400;
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @return A list containing the interviewTypes.
     */
    public java.util.List<com.hiresphere.profile.grpc.InterviewType> getInterviewTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.hiresphere.profile.grpc.InterviewType>(interviewTypes_, interviewTypes_converter_);
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @return The count of interviewTypes.
     */
    public int getInterviewTypesCount() {
      return interviewTypes_.size();
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param index The index of the element to return.
     * @return The interviewTypes at the given index.
     */
    public com.hiresphere.profile.grpc.InterviewType getInterviewTypes(int index) {
      return interviewTypes_converter_.convert(interviewTypes_.get(index));
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param index The index to set the value at.
     * @param value The interviewTypes to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewTypes(
        int index, com.hiresphere.profile.grpc.InterviewType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureInterviewTypesIsMutable();
      interviewTypes_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param value The interviewTypes to add.
     * @return This builder for chaining.
     */
    public Builder addInterviewTypes(com.hiresphere.profile.grpc.InterviewType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureInterviewTypesIsMutable();
      interviewTypes_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param values The interviewTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllInterviewTypes(
        java.lang.Iterable<? extends com.hiresphere.profile.grpc.InterviewType> values) {
      ensureInterviewTypesIsMutable();
      for (com.hiresphere.profile.grpc.InterviewType value : values) {
        interviewTypes_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterviewTypes() {
      interviewTypes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @return A list containing the enum numeric values on the wire for interviewTypes.
     */
    public java.util.List<java.lang.Integer>
    getInterviewTypesValueList() {
      return java.util.Collections.unmodifiableList(interviewTypes_);
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of interviewTypes at the given index.
     */
    public int getInterviewTypesValue(int index) {
      return interviewTypes_.get(index);
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for interviewTypes to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewTypesValue(
        int index, int value) {
      ensureInterviewTypesIsMutable();
      interviewTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param value The enum numeric value on the wire for interviewTypes to add.
     * @return This builder for chaining.
     */
    public Builder addInterviewTypesValue(int value) {
      ensureInterviewTypesIsMutable();
      interviewTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.InterviewType interview_types = 11;</code>
     * @param values The enum numeric values on the wire for interviewTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllInterviewTypesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureInterviewTypesIsMutable();
      for (int value : values) {
        interviewTypes_.add(value);
      }
      onChanged();
      return this;
    }

    private java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot> availability_ =
      java.util.Collections.emptyList();
    private void ensureAvailabilityIsMutable() {
      if (!((bitField0_ & 0x00000800) != 0)) {
        availability_ = new java.util.ArrayList<com.hiresphere.profile.grpc.AvailabilitySlot>(availability_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hiresphere.profile.grpc.AvailabilitySlot, com.hiresphere.profile.grpc.AvailabilitySlot.Builder, com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder> availabilityBuilder_;

    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot> getAvailabilityList() {
      if (availabilityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(availability_);
      } else {
        return availabilityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public int getAvailabilityCount() {
      if (availabilityBuilder_ == null) {
        return availability_.size();
      } else {
        return availabilityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public com.hiresphere.profile.grpc.AvailabilitySlot getAvailability(int index) {
      if (availabilityBuilder_ == null) {
        return availability_.get(index);
      } else {
        return availabilityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder setAvailability(
        int index, com.hiresphere.profile.grpc.AvailabilitySlot value) {
      if (availabilityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilityIsMutable();
        availability_.set(index, value);
        onChanged();
      } else {
        availabilityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder setAvailability(
        int index, com.hiresphere.profile.grpc.AvailabilitySlot.Builder builderForValue) {
      if (availabilityBuilder_ == null) {
        ensureAvailabilityIsMutable();
        availability_.set(index, builderForValue.build());
        onChanged();
      } else {
        availabilityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder addAvailability(com.hiresphere.profile.grpc.AvailabilitySlot value) {
      if (availabilityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilityIsMutable();
        availability_.add(value);
        onChanged();
      } else {
        availabilityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder addAvailability(
        int index, com.hiresphere.profile.grpc.AvailabilitySlot value) {
      if (availabilityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailabilityIsMutable();
        availability_.add(index, value);
        onChanged();
      } else {
        availabilityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder addAvailability(
        com.hiresphere.profile.grpc.AvailabilitySlot.Builder builderForValue) {
      if (availabilityBuilder_ == null) {
        ensureAvailabilityIsMutable();
        availability_.add(builderForValue.build());
        onChanged();
      } else {
        availabilityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder addAvailability(
        int index, com.hiresphere.profile.grpc.AvailabilitySlot.Builder builderForValue) {
      if (availabilityBuilder_ == null) {
        ensureAvailabilityIsMutable();
        availability_.add(index, builderForValue.build());
        onChanged();
      } else {
        availabilityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder addAllAvailability(
        java.lang.Iterable<? extends com.hiresphere.profile.grpc.AvailabilitySlot> values) {
      if (availabilityBuilder_ == null) {
        ensureAvailabilityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, availability_);
        onChanged();
      } else {
        availabilityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder clearAvailability() {
      if (availabilityBuilder_ == null) {
        availability_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        availabilityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public Builder removeAvailability(int index) {
      if (availabilityBuilder_ == null) {
        ensureAvailabilityIsMutable();
        availability_.remove(index);
        onChanged();
      } else {
        availabilityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public com.hiresphere.profile.grpc.AvailabilitySlot.Builder getAvailabilityBuilder(
        int index) {
      return getAvailabilityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder getAvailabilityOrBuilder(
        int index) {
      if (availabilityBuilder_ == null) {
        return availability_.get(index);  } else {
        return availabilityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public java.util.List<? extends com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder> 
         getAvailabilityOrBuilderList() {
      if (availabilityBuilder_ != null) {
        return availabilityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(availability_);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public com.hiresphere.profile.grpc.AvailabilitySlot.Builder addAvailabilityBuilder() {
      return getAvailabilityFieldBuilder().addBuilder(
          com.hiresphere.profile.grpc.AvailabilitySlot.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public com.hiresphere.profile.grpc.AvailabilitySlot.Builder addAvailabilityBuilder(
        int index) {
      return getAvailabilityFieldBuilder().addBuilder(
          index, com.hiresphere.profile.grpc.AvailabilitySlot.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hiresphere.profile.AvailabilitySlot availability = 12;</code>
     */
    public java.util.List<com.hiresphere.profile.grpc.AvailabilitySlot.Builder> 
         getAvailabilityBuilderList() {
      return getAvailabilityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hiresphere.profile.grpc.AvailabilitySlot, com.hiresphere.profile.grpc.AvailabilitySlot.Builder, com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder> 
        getAvailabilityFieldBuilder() {
      if (availabilityBuilder_ == null) {
        availabilityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hiresphere.profile.grpc.AvailabilitySlot, com.hiresphere.profile.grpc.AvailabilitySlot.Builder, com.hiresphere.profile.grpc.AvailabilitySlotOrBuilder>(
                availability_,
                ((bitField0_ & 0x00000800) != 0),
                getParentForChildren(),
                isClean());
        availability_ = null;
      }
      return availabilityBuilder_;
    }

    private java.lang.Object avatarUrl_ = "";
    /**
     * <code>string avatar_url = 13;</code>
     * @return The avatarUrl.
     */
    public java.lang.String getAvatarUrl() {
      java.lang.Object ref = avatarUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar_url = 13;</code>
     * @return The bytes for avatarUrl.
     */
    public com.google.protobuf.ByteString
        getAvatarUrlBytes() {
      java.lang.Object ref = avatarUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar_url = 13;</code>
     * @param value The avatarUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      avatarUrl_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_url = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatarUrl() {
      avatarUrl_ = getDefaultInstance().getAvatarUrl();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_url = 13;</code>
     * @param value The bytes for avatarUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      avatarUrl_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int pricePerHour_ ;
    /**
     * <code>int32 price_per_hour = 14;</code>
     * @return The pricePerHour.
     */
    @java.lang.Override
    public int getPricePerHour() {
      return pricePerHour_;
    }
    /**
     * <code>int32 price_per_hour = 14;</code>
     * @param value The pricePerHour to set.
     * @return This builder for chaining.
     */
    public Builder setPricePerHour(int value) {

      pricePerHour_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 price_per_hour = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPricePerHour() {
      bitField0_ = (bitField0_ & ~0x00002000);
      pricePerHour_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object linkedinUrl_ = "";
    /**
     * <code>string linkedin_url = 15;</code>
     * @return The linkedinUrl.
     */
    public java.lang.String getLinkedinUrl() {
      java.lang.Object ref = linkedinUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkedinUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string linkedin_url = 15;</code>
     * @return The bytes for linkedinUrl.
     */
    public com.google.protobuf.ByteString
        getLinkedinUrlBytes() {
      java.lang.Object ref = linkedinUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkedinUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string linkedin_url = 15;</code>
     * @param value The linkedinUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedinUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      linkedinUrl_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string linkedin_url = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkedinUrl() {
      linkedinUrl_ = getDefaultInstance().getLinkedinUrl();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string linkedin_url = 15;</code>
     * @param value The bytes for linkedinUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedinUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      linkedinUrl_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private java.lang.Object githubUrl_ = "";
    /**
     * <code>string github_url = 16;</code>
     * @return The githubUrl.
     */
    public java.lang.String getGithubUrl() {
      java.lang.Object ref = githubUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        githubUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string github_url = 16;</code>
     * @return The bytes for githubUrl.
     */
    public com.google.protobuf.ByteString
        getGithubUrlBytes() {
      java.lang.Object ref = githubUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        githubUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string github_url = 16;</code>
     * @param value The githubUrl to set.
     * @return This builder for chaining.
     */
    public Builder setGithubUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      githubUrl_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>string github_url = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearGithubUrl() {
      githubUrl_ = getDefaultInstance().getGithubUrl();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }
    /**
     * <code>string github_url = 16;</code>
     * @param value The bytes for githubUrl to set.
     * @return This builder for chaining.
     */
    public Builder setGithubUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      githubUrl_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>int64 created_at = 17;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>int64 created_at = 17;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 created_at = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00010000);
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private long updatedAt_ ;
    /**
     * <code>int64 updated_at = 18;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>int64 updated_at = 18;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {

      updatedAt_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 updated_at = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00020000);
      updatedAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.profile.Profile)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.profile.Profile)
  private static final com.hiresphere.profile.grpc.Profile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.profile.grpc.Profile();
  }

  public static com.hiresphere.profile.grpc.Profile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Profile>
      PARSER = new com.google.protobuf.AbstractParser<Profile>() {
    @java.lang.Override
    public Profile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Profile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Profile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.profile.grpc.Profile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

