// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public final class ProfileOuterClass {
  private ProfileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_Profile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_Profile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_AvailabilitySlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_AvailabilitySlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_GetProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_GetProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_GetProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_GetProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_CreateProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_CreateProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_CreateProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_CreateProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_UpdateProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_UpdateProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_UpdateProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_UpdateProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_SearchInterviewersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_SearchInterviewersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_GetAvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_GetAvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_GetAvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_GetAvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_UpdateRatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_UpdateRatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_profile_UpdateRatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_profile_UpdateRatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprofile.proto\022\026com.hiresphere.profile\"" +
      "\337\003\n\007Profile\022\017\n\007user_id\030\001 \001(\t\022\014\n\004name\030\002 \001" +
      "(\t\022\r\n\005email\030\003 \001(\t\0229\n\014profile_type\030\004 \001(\0162" +
      "#.com.hiresphere.profile.ProfileType\022\013\n\003" +
      "bio\030\005 \001(\t\022\017\n\007domains\030\006 \003(\t\022\016\n\006badges\030\007 \003" +
      "(\t\022\016\n\006rating\030\010 \001(\002\022\025\n\rtotal_reviews\030\t \001(" +
      "\005\022\030\n\020years_experience\030\n \001(\005\022>\n\017interview" +
      "_types\030\013 \003(\0162%.com.hiresphere.profile.In" +
      "terviewType\022>\n\014availability\030\014 \003(\0132(.com." +
      "hiresphere.profile.AvailabilitySlot\022\022\n\na" +
      "vatar_url\030\r \001(\t\022\026\n\016price_per_hour\030\016 \001(\005\022" +
      "\024\n\014linkedin_url\030\017 \001(\t\022\022\n\ngithub_url\030\020 \001(" +
      "\t\022\022\n\ncreated_at\030\021 \001(\003\022\022\n\nupdated_at\030\022 \001(" +
      "\003\"\\\n\020AvailabilitySlot\022\017\n\007slot_id\030\001 \001(\t\022\022" +
      "\n\nstart_time\030\002 \001(\003\022\020\n\010end_time\030\003 \001(\003\022\021\n\t" +
      "is_booked\030\004 \001(\010\"$\n\021GetProfileRequest\022\017\n\007" +
      "user_id\030\001 \001(\t\"U\n\022GetProfileResponse\0220\n\007p" +
      "rofile\030\001 \001(\0132\037.com.hiresphere.profile.Pr" +
      "ofile\022\r\n\005found\030\002 \001(\010\"H\n\024CreateProfileReq" +
      "uest\0220\n\007profile\030\001 \001(\0132\037.com.hiresphere.p" +
      "rofile.Profile\"k\n\025CreateProfileResponse\022" +
      "0\n\007profile\030\001 \001(\0132\037.com.hiresphere.profil" +
      "e.Profile\022\017\n\007success\030\002 \001(\010\022\017\n\007message\030\003 " +
      "\001(\t\"H\n\024UpdateProfileRequest\0220\n\007profile\030\001" +
      " \001(\0132\037.com.hiresphere.profile.Profile\"Z\n" +
      "\025UpdateProfileResponse\0220\n\007profile\030\001 \001(\0132" +
      "\037.com.hiresphere.profile.Profile\022\017\n\007succ" +
      "ess\030\002 \001(\010\"\312\001\n\031SearchInterviewersRequest\022" +
      "\016\n\006domain\030\001 \001(\t\022=\n\016interview_type\030\002 \001(\0162" +
      "%.com.hiresphere.profile.InterviewType\022\026" +
      "\n\016min_experience\030\003 \001(\005\022\022\n\nmin_rating\030\004 \001" +
      "(\002\022\021\n\tmax_price\030\005 \001(\005\022\014\n\004page\030\006 \001(\005\022\021\n\tp" +
      "age_size\030\007 \001(\005\"p\n\032SearchInterviewersResp" +
      "onse\0225\n\014interviewers\030\001 \003(\0132\037.com.hiresph" +
      "ere.profile.Profile\022\r\n\005total\030\002 \001(\005\022\014\n\004pa" +
      "ge\030\003 \001(\005\"O\n\026GetAvailabilityRequest\022\017\n\007us" +
      "er_id\030\001 \001(\t\022\022\n\nfrom_epoch\030\002 \001(\003\022\020\n\010to_ep" +
      "och\030\003 \001(\003\"R\n\027GetAvailabilityResponse\0227\n\005" +
      "slots\030\001 \003(\0132(.com.hiresphere.profile.Ava" +
      "ilabilitySlot\"P\n\023UpdateRatingRequest\022\017\n\007" +
      "user_id\030\001 \001(\t\022\022\n\nnew_rating\030\002 \001(\002\022\024\n\014rev" +
      "iew_count\030\003 \001(\005\"\'\n\024UpdateRatingResponse\022" +
      "\017\n\007success\030\001 \001(\010*-\n\013ProfileType\022\r\n\tCANDI" +
      "DATE\020\000\022\017\n\013INTERVIEWER\020\001*}\n\rInterviewType" +
      "\022\021\n\rSYSTEM_DESIGN\020\000\022\023\n\017DATA_STRUCTURES\020\001" +
      "\022\016\n\nBEHAVIORAL\020\002\022\014\n\010FRONTEND\020\003\022\013\n\007BACKEN" +
      "D\020\004\022\r\n\tFULLSTACK\020\005\022\n\n\006DEVOPS\020\0062\255\005\n\016Profi" +
      "leService\022c\n\nGetProfile\022).com.hiresphere" +
      ".profile.GetProfileRequest\032*.com.hiresph" +
      "ere.profile.GetProfileResponse\022l\n\rCreate" +
      "Profile\022,.com.hiresphere.profile.CreateP" +
      "rofileRequest\032-.com.hiresphere.profile.C" +
      "reateProfileResponse\022l\n\rUpdateProfile\022,." +
      "com.hiresphere.profile.UpdateProfileRequ" +
      "est\032-.com.hiresphere.profile.UpdateProfi" +
      "leResponse\022{\n\022SearchInterviewers\0221.com.h" +
      "iresphere.profile.SearchInterviewersRequ" +
      "est\0322.com.hiresphere.profile.SearchInter" +
      "viewersResponse\022r\n\017GetAvailability\022..com" +
      ".hiresphere.profile.GetAvailabilityReque" +
      "st\032/.com.hiresphere.profile.GetAvailabil" +
      "ityResponse\022i\n\014UpdateRating\022+.com.hiresp" +
      "here.profile.UpdateRatingRequest\032,.com.h" +
      "iresphere.profile.UpdateRatingResponseB\037" +
      "\n\033com.hiresphere.profile.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hiresphere_profile_Profile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hiresphere_profile_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_Profile_descriptor,
        new java.lang.String[] { "UserId", "Name", "Email", "ProfileType", "Bio", "Domains", "Badges", "Rating", "TotalReviews", "YearsExperience", "InterviewTypes", "Availability", "AvatarUrl", "PricePerHour", "LinkedinUrl", "GithubUrl", "CreatedAt", "UpdatedAt", });
    internal_static_com_hiresphere_profile_AvailabilitySlot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hiresphere_profile_AvailabilitySlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_AvailabilitySlot_descriptor,
        new java.lang.String[] { "SlotId", "StartTime", "EndTime", "IsBooked", });
    internal_static_com_hiresphere_profile_GetProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hiresphere_profile_GetProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_GetProfileRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_hiresphere_profile_GetProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hiresphere_profile_GetProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_GetProfileResponse_descriptor,
        new java.lang.String[] { "Profile", "Found", });
    internal_static_com_hiresphere_profile_CreateProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hiresphere_profile_CreateProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_CreateProfileRequest_descriptor,
        new java.lang.String[] { "Profile", });
    internal_static_com_hiresphere_profile_CreateProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_hiresphere_profile_CreateProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_CreateProfileResponse_descriptor,
        new java.lang.String[] { "Profile", "Success", "Message", });
    internal_static_com_hiresphere_profile_UpdateProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_hiresphere_profile_UpdateProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_UpdateProfileRequest_descriptor,
        new java.lang.String[] { "Profile", });
    internal_static_com_hiresphere_profile_UpdateProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_hiresphere_profile_UpdateProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_UpdateProfileResponse_descriptor,
        new java.lang.String[] { "Profile", "Success", });
    internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_hiresphere_profile_SearchInterviewersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor,
        new java.lang.String[] { "Domain", "InterviewType", "MinExperience", "MinRating", "MaxPrice", "Page", "PageSize", });
    internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_hiresphere_profile_SearchInterviewersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor,
        new java.lang.String[] { "Interviewers", "Total", "Page", });
    internal_static_com_hiresphere_profile_GetAvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_hiresphere_profile_GetAvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_GetAvailabilityRequest_descriptor,
        new java.lang.String[] { "UserId", "FromEpoch", "ToEpoch", });
    internal_static_com_hiresphere_profile_GetAvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_hiresphere_profile_GetAvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_GetAvailabilityResponse_descriptor,
        new java.lang.String[] { "Slots", });
    internal_static_com_hiresphere_profile_UpdateRatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_hiresphere_profile_UpdateRatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_UpdateRatingRequest_descriptor,
        new java.lang.String[] { "UserId", "NewRating", "ReviewCount", });
    internal_static_com_hiresphere_profile_UpdateRatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_hiresphere_profile_UpdateRatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_profile_UpdateRatingResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
