// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * Protobuf type {@code com.hiresphere.profile.SearchInterviewersResponse}
 */
public final class SearchInterviewersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.profile.SearchInterviewersResponse)
    SearchInterviewersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchInterviewersResponse.newBuilder() to construct.
  private SearchInterviewersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchInterviewersResponse() {
    interviewers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchInterviewersResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.profile.grpc.SearchInterviewersResponse.class, com.hiresphere.profile.grpc.SearchInterviewersResponse.Builder.class);
  }

  public static final int INTERVIEWERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.hiresphere.profile.grpc.Profile> interviewers_;
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.hiresphere.profile.grpc.Profile> getInterviewersList() {
    return interviewers_;
  }
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.hiresphere.profile.grpc.ProfileOrBuilder> 
      getInterviewersOrBuilderList() {
    return interviewers_;
  }
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  @java.lang.Override
  public int getInterviewersCount() {
    return interviewers_.size();
  }
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.Profile getInterviewers(int index) {
    return interviewers_.get(index);
  }
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  @java.lang.Override
  public com.hiresphere.profile.grpc.ProfileOrBuilder getInterviewersOrBuilder(
      int index) {
    return interviewers_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private int page_ = 0;
  /**
   * <code>int32 page = 3;</code>
   * @return The page.
   */
  @java.lang.Override
  public int getPage() {
    return page_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < interviewers_.size(); i++) {
      output.writeMessage(1, interviewers_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    if (page_ != 0) {
      output.writeInt32(3, page_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < interviewers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, interviewers_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, page_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.profile.grpc.SearchInterviewersResponse)) {
      return super.equals(obj);
    }
    com.hiresphere.profile.grpc.SearchInterviewersResponse other = (com.hiresphere.profile.grpc.SearchInterviewersResponse) obj;

    if (!getInterviewersList()
        .equals(other.getInterviewersList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (getPage()
        != other.getPage()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInterviewersCount() > 0) {
      hash = (37 * hash) + INTERVIEWERS_FIELD_NUMBER;
      hash = (53 * hash) + getInterviewersList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.profile.grpc.SearchInterviewersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hiresphere.profile.SearchInterviewersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.profile.SearchInterviewersResponse)
      com.hiresphere.profile.grpc.SearchInterviewersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.profile.grpc.SearchInterviewersResponse.class, com.hiresphere.profile.grpc.SearchInterviewersResponse.Builder.class);
    }

    // Construct using com.hiresphere.profile.grpc.SearchInterviewersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (interviewersBuilder_ == null) {
        interviewers_ = java.util.Collections.emptyList();
      } else {
        interviewers_ = null;
        interviewersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      page_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersResponse_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersResponse getDefaultInstanceForType() {
      return com.hiresphere.profile.grpc.SearchInterviewersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersResponse build() {
      com.hiresphere.profile.grpc.SearchInterviewersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersResponse buildPartial() {
      com.hiresphere.profile.grpc.SearchInterviewersResponse result = new com.hiresphere.profile.grpc.SearchInterviewersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.hiresphere.profile.grpc.SearchInterviewersResponse result) {
      if (interviewersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          interviewers_ = java.util.Collections.unmodifiableList(interviewers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.interviewers_ = interviewers_;
      } else {
        result.interviewers_ = interviewersBuilder_.build();
      }
    }

    private void buildPartial0(com.hiresphere.profile.grpc.SearchInterviewersResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = page_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.profile.grpc.SearchInterviewersResponse) {
        return mergeFrom((com.hiresphere.profile.grpc.SearchInterviewersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.profile.grpc.SearchInterviewersResponse other) {
      if (other == com.hiresphere.profile.grpc.SearchInterviewersResponse.getDefaultInstance()) return this;
      if (interviewersBuilder_ == null) {
        if (!other.interviewers_.isEmpty()) {
          if (interviewers_.isEmpty()) {
            interviewers_ = other.interviewers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInterviewersIsMutable();
            interviewers_.addAll(other.interviewers_);
          }
          onChanged();
        }
      } else {
        if (!other.interviewers_.isEmpty()) {
          if (interviewersBuilder_.isEmpty()) {
            interviewersBuilder_.dispose();
            interviewersBuilder_ = null;
            interviewers_ = other.interviewers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            interviewersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInterviewersFieldBuilder() : null;
          } else {
            interviewersBuilder_.addAllMessages(other.interviewers_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.hiresphere.profile.grpc.Profile m =
                  input.readMessage(
                      com.hiresphere.profile.grpc.Profile.parser(),
                      extensionRegistry);
              if (interviewersBuilder_ == null) {
                ensureInterviewersIsMutable();
                interviewers_.add(m);
              } else {
                interviewersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              page_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hiresphere.profile.grpc.Profile> interviewers_ =
      java.util.Collections.emptyList();
    private void ensureInterviewersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        interviewers_ = new java.util.ArrayList<com.hiresphere.profile.grpc.Profile>(interviewers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder> interviewersBuilder_;

    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public java.util.List<com.hiresphere.profile.grpc.Profile> getInterviewersList() {
      if (interviewersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(interviewers_);
      } else {
        return interviewersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public int getInterviewersCount() {
      if (interviewersBuilder_ == null) {
        return interviewers_.size();
      } else {
        return interviewersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public com.hiresphere.profile.grpc.Profile getInterviewers(int index) {
      if (interviewersBuilder_ == null) {
        return interviewers_.get(index);
      } else {
        return interviewersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder setInterviewers(
        int index, com.hiresphere.profile.grpc.Profile value) {
      if (interviewersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInterviewersIsMutable();
        interviewers_.set(index, value);
        onChanged();
      } else {
        interviewersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder setInterviewers(
        int index, com.hiresphere.profile.grpc.Profile.Builder builderForValue) {
      if (interviewersBuilder_ == null) {
        ensureInterviewersIsMutable();
        interviewers_.set(index, builderForValue.build());
        onChanged();
      } else {
        interviewersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder addInterviewers(com.hiresphere.profile.grpc.Profile value) {
      if (interviewersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInterviewersIsMutable();
        interviewers_.add(value);
        onChanged();
      } else {
        interviewersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder addInterviewers(
        int index, com.hiresphere.profile.grpc.Profile value) {
      if (interviewersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInterviewersIsMutable();
        interviewers_.add(index, value);
        onChanged();
      } else {
        interviewersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder addInterviewers(
        com.hiresphere.profile.grpc.Profile.Builder builderForValue) {
      if (interviewersBuilder_ == null) {
        ensureInterviewersIsMutable();
        interviewers_.add(builderForValue.build());
        onChanged();
      } else {
        interviewersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder addInterviewers(
        int index, com.hiresphere.profile.grpc.Profile.Builder builderForValue) {
      if (interviewersBuilder_ == null) {
        ensureInterviewersIsMutable();
        interviewers_.add(index, builderForValue.build());
        onChanged();
      } else {
        interviewersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder addAllInterviewers(
        java.lang.Iterable<? extends com.hiresphere.profile.grpc.Profile> values) {
      if (interviewersBuilder_ == null) {
        ensureInterviewersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, interviewers_);
        onChanged();
      } else {
        interviewersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder clearInterviewers() {
      if (interviewersBuilder_ == null) {
        interviewers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        interviewersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public Builder removeInterviewers(int index) {
      if (interviewersBuilder_ == null) {
        ensureInterviewersIsMutable();
        interviewers_.remove(index);
        onChanged();
      } else {
        interviewersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public com.hiresphere.profile.grpc.Profile.Builder getInterviewersBuilder(
        int index) {
      return getInterviewersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public com.hiresphere.profile.grpc.ProfileOrBuilder getInterviewersOrBuilder(
        int index) {
      if (interviewersBuilder_ == null) {
        return interviewers_.get(index);  } else {
        return interviewersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public java.util.List<? extends com.hiresphere.profile.grpc.ProfileOrBuilder> 
         getInterviewersOrBuilderList() {
      if (interviewersBuilder_ != null) {
        return interviewersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(interviewers_);
      }
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public com.hiresphere.profile.grpc.Profile.Builder addInterviewersBuilder() {
      return getInterviewersFieldBuilder().addBuilder(
          com.hiresphere.profile.grpc.Profile.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public com.hiresphere.profile.grpc.Profile.Builder addInterviewersBuilder(
        int index) {
      return getInterviewersFieldBuilder().addBuilder(
          index, com.hiresphere.profile.grpc.Profile.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
     */
    public java.util.List<com.hiresphere.profile.grpc.Profile.Builder> 
         getInterviewersBuilderList() {
      return getInterviewersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder> 
        getInterviewersFieldBuilder() {
      if (interviewersBuilder_ == null) {
        interviewersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hiresphere.profile.grpc.Profile, com.hiresphere.profile.grpc.Profile.Builder, com.hiresphere.profile.grpc.ProfileOrBuilder>(
                interviewers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        interviewers_ = null;
      }
      return interviewersBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 3;</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 3;</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(int value) {

      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.profile.SearchInterviewersResponse)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.profile.SearchInterviewersResponse)
  private static final com.hiresphere.profile.grpc.SearchInterviewersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.profile.grpc.SearchInterviewersResponse();
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchInterviewersResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchInterviewersResponse>() {
    @java.lang.Override
    public SearchInterviewersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchInterviewersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchInterviewersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.profile.grpc.SearchInterviewersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

