// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public interface SearchInterviewersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.profile.SearchInterviewersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  java.util.List<com.hiresphere.profile.grpc.Profile> 
      getInterviewersList();
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  com.hiresphere.profile.grpc.Profile getInterviewers(int index);
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  int getInterviewersCount();
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  java.util.List<? extends com.hiresphere.profile.grpc.ProfileOrBuilder> 
      getInterviewersOrBuilderList();
  /**
   * <code>repeated .com.hiresphere.profile.Profile interviewers = 1;</code>
   */
  com.hiresphere.profile.grpc.ProfileOrBuilder getInterviewersOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <code>int32 page = 3;</code>
   * @return The page.
   */
  int getPage();
}
