// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public interface SearchInterviewersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.profile.SearchInterviewersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string domain = 1;</code>
   * @return The domain.
   */
  java.lang.String getDomain();
  /**
   * <code>string domain = 1;</code>
   * @return The bytes for domain.
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
   * @return The enum numeric value on the wire for interviewType.
   */
  int getInterviewTypeValue();
  /**
   * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
   * @return The interviewType.
   */
  com.hiresphere.profile.grpc.InterviewType getInterviewType();

  /**
   * <code>int32 min_experience = 3;</code>
   * @return The minExperience.
   */
  int getMinExperience();

  /**
   * <code>float min_rating = 4;</code>
   * @return The minRating.
   */
  float getMinRating();

  /**
   * <code>int32 max_price = 5;</code>
   * @return The maxPrice.
   */
  int getMaxPrice();

  /**
   * <code>int32 page = 6;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 page_size = 7;</code>
   * @return The pageSize.
   */
  int getPageSize();
}
