// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

/**
 * Protobuf type {@code com.hiresphere.profile.SearchInterviewersRequest}
 */
public final class SearchInterviewersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.profile.SearchInterviewersRequest)
    SearchInterviewersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchInterviewersRequest.newBuilder() to construct.
  private SearchInterviewersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchInterviewersRequest() {
    domain_ = "";
    interviewType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchInterviewersRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.profile.grpc.SearchInterviewersRequest.class, com.hiresphere.profile.grpc.SearchInterviewersRequest.Builder.class);
  }

  public static final int DOMAIN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <code>string domain = 1;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <code>string domain = 1;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERVIEW_TYPE_FIELD_NUMBER = 2;
  private int interviewType_ = 0;
  /**
   * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
   * @return The enum numeric value on the wire for interviewType.
   */
  @java.lang.Override public int getInterviewTypeValue() {
    return interviewType_;
  }
  /**
   * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
   * @return The interviewType.
   */
  @java.lang.Override public com.hiresphere.profile.grpc.InterviewType getInterviewType() {
    com.hiresphere.profile.grpc.InterviewType result = com.hiresphere.profile.grpc.InterviewType.forNumber(interviewType_);
    return result == null ? com.hiresphere.profile.grpc.InterviewType.UNRECOGNIZED : result;
  }

  public static final int MIN_EXPERIENCE_FIELD_NUMBER = 3;
  private int minExperience_ = 0;
  /**
   * <code>int32 min_experience = 3;</code>
   * @return The minExperience.
   */
  @java.lang.Override
  public int getMinExperience() {
    return minExperience_;
  }

  public static final int MIN_RATING_FIELD_NUMBER = 4;
  private float minRating_ = 0F;
  /**
   * <code>float min_rating = 4;</code>
   * @return The minRating.
   */
  @java.lang.Override
  public float getMinRating() {
    return minRating_;
  }

  public static final int MAX_PRICE_FIELD_NUMBER = 5;
  private int maxPrice_ = 0;
  /**
   * <code>int32 max_price = 5;</code>
   * @return The maxPrice.
   */
  @java.lang.Override
  public int getMaxPrice() {
    return maxPrice_;
  }

  public static final int PAGE_FIELD_NUMBER = 6;
  private int page_ = 0;
  /**
   * <code>int32 page = 6;</code>
   * @return The page.
   */
  @java.lang.Override
  public int getPage() {
    return page_;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 7;
  private int pageSize_ = 0;
  /**
   * <code>int32 page_size = 7;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_);
    }
    if (interviewType_ != com.hiresphere.profile.grpc.InterviewType.SYSTEM_DESIGN.getNumber()) {
      output.writeEnum(2, interviewType_);
    }
    if (minExperience_ != 0) {
      output.writeInt32(3, minExperience_);
    }
    if (java.lang.Float.floatToRawIntBits(minRating_) != 0) {
      output.writeFloat(4, minRating_);
    }
    if (maxPrice_ != 0) {
      output.writeInt32(5, maxPrice_);
    }
    if (page_ != 0) {
      output.writeInt32(6, page_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(7, pageSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domain_);
    }
    if (interviewType_ != com.hiresphere.profile.grpc.InterviewType.SYSTEM_DESIGN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, interviewType_);
    }
    if (minExperience_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, minExperience_);
    }
    if (java.lang.Float.floatToRawIntBits(minRating_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, minRating_);
    }
    if (maxPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxPrice_);
    }
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, page_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, pageSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.profile.grpc.SearchInterviewersRequest)) {
      return super.equals(obj);
    }
    com.hiresphere.profile.grpc.SearchInterviewersRequest other = (com.hiresphere.profile.grpc.SearchInterviewersRequest) obj;

    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (interviewType_ != other.interviewType_) return false;
    if (getMinExperience()
        != other.getMinExperience()) return false;
    if (java.lang.Float.floatToIntBits(getMinRating())
        != java.lang.Float.floatToIntBits(
            other.getMinRating())) return false;
    if (getMaxPrice()
        != other.getMaxPrice()) return false;
    if (getPage()
        != other.getPage()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (37 * hash) + INTERVIEW_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + interviewType_;
    hash = (37 * hash) + MIN_EXPERIENCE_FIELD_NUMBER;
    hash = (53 * hash) + getMinExperience();
    hash = (37 * hash) + MIN_RATING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinRating());
    hash = (37 * hash) + MAX_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxPrice();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.profile.grpc.SearchInterviewersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.profile.grpc.SearchInterviewersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hiresphere.profile.SearchInterviewersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.profile.SearchInterviewersRequest)
      com.hiresphere.profile.grpc.SearchInterviewersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.profile.grpc.SearchInterviewersRequest.class, com.hiresphere.profile.grpc.SearchInterviewersRequest.Builder.class);
    }

    // Construct using com.hiresphere.profile.grpc.SearchInterviewersRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      domain_ = "";
      interviewType_ = 0;
      minExperience_ = 0;
      minRating_ = 0F;
      maxPrice_ = 0;
      page_ = 0;
      pageSize_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.profile.grpc.ProfileOuterClass.internal_static_com_hiresphere_profile_SearchInterviewersRequest_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersRequest getDefaultInstanceForType() {
      return com.hiresphere.profile.grpc.SearchInterviewersRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersRequest build() {
      com.hiresphere.profile.grpc.SearchInterviewersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.profile.grpc.SearchInterviewersRequest buildPartial() {
      com.hiresphere.profile.grpc.SearchInterviewersRequest result = new com.hiresphere.profile.grpc.SearchInterviewersRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hiresphere.profile.grpc.SearchInterviewersRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.domain_ = domain_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.interviewType_ = interviewType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minExperience_ = minExperience_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.minRating_ = minRating_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxPrice_ = maxPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.page_ = page_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.pageSize_ = pageSize_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.profile.grpc.SearchInterviewersRequest) {
        return mergeFrom((com.hiresphere.profile.grpc.SearchInterviewersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.profile.grpc.SearchInterviewersRequest other) {
      if (other == com.hiresphere.profile.grpc.SearchInterviewersRequest.getDefaultInstance()) return this;
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.interviewType_ != 0) {
        setInterviewTypeValue(other.getInterviewTypeValue());
      }
      if (other.getMinExperience() != 0) {
        setMinExperience(other.getMinExperience());
      }
      if (other.getMinRating() != 0F) {
        setMinRating(other.getMinRating());
      }
      if (other.getMaxPrice() != 0) {
        setMaxPrice(other.getMaxPrice());
      }
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              interviewType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              minExperience_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 37: {
              minRating_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 40: {
              maxPrice_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              page_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              pageSize_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object domain_ = "";
    /**
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain = 1;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 1;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int interviewType_ = 0;
    /**
     * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
     * @return The enum numeric value on the wire for interviewType.
     */
    @java.lang.Override public int getInterviewTypeValue() {
      return interviewType_;
    }
    /**
     * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
     * @param value The enum numeric value on the wire for interviewType to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewTypeValue(int value) {
      interviewType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
     * @return The interviewType.
     */
    @java.lang.Override
    public com.hiresphere.profile.grpc.InterviewType getInterviewType() {
      com.hiresphere.profile.grpc.InterviewType result = com.hiresphere.profile.grpc.InterviewType.forNumber(interviewType_);
      return result == null ? com.hiresphere.profile.grpc.InterviewType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
     * @param value The interviewType to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewType(com.hiresphere.profile.grpc.InterviewType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      interviewType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.profile.InterviewType interview_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterviewType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      interviewType_ = 0;
      onChanged();
      return this;
    }

    private int minExperience_ ;
    /**
     * <code>int32 min_experience = 3;</code>
     * @return The minExperience.
     */
    @java.lang.Override
    public int getMinExperience() {
      return minExperience_;
    }
    /**
     * <code>int32 min_experience = 3;</code>
     * @param value The minExperience to set.
     * @return This builder for chaining.
     */
    public Builder setMinExperience(int value) {

      minExperience_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 min_experience = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinExperience() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minExperience_ = 0;
      onChanged();
      return this;
    }

    private float minRating_ ;
    /**
     * <code>float min_rating = 4;</code>
     * @return The minRating.
     */
    @java.lang.Override
    public float getMinRating() {
      return minRating_;
    }
    /**
     * <code>float min_rating = 4;</code>
     * @param value The minRating to set.
     * @return This builder for chaining.
     */
    public Builder setMinRating(float value) {

      minRating_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float min_rating = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinRating() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minRating_ = 0F;
      onChanged();
      return this;
    }

    private int maxPrice_ ;
    /**
     * <code>int32 max_price = 5;</code>
     * @return The maxPrice.
     */
    @java.lang.Override
    public int getMaxPrice() {
      return maxPrice_;
    }
    /**
     * <code>int32 max_price = 5;</code>
     * @param value The maxPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPrice(int value) {

      maxPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPrice() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxPrice_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 6;</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 6;</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(int value) {

      page_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      page_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 page_size = 7;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 page_size = 7;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {

      pageSize_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page_size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      bitField0_ = (bitField0_ & ~0x00000040);
      pageSize_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.profile.SearchInterviewersRequest)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.profile.SearchInterviewersRequest)
  private static final com.hiresphere.profile.grpc.SearchInterviewersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.profile.grpc.SearchInterviewersRequest();
  }

  public static com.hiresphere.profile.grpc.SearchInterviewersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchInterviewersRequest>
      PARSER = new com.google.protobuf.AbstractParser<SearchInterviewersRequest>() {
    @java.lang.Override
    public SearchInterviewersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchInterviewersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchInterviewersRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.profile.grpc.SearchInterviewersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

