// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public interface UpdateProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.profile.UpdateProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   * @return Whether the profile field is set.
   */
  boolean hasProfile();
  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   * @return The profile.
   */
  com.hiresphere.profile.grpc.Profile getProfile();
  /**
   * <code>.com.hiresphere.profile.Profile profile = 1;</code>
   */
  com.hiresphere.profile.grpc.ProfileOrBuilder getProfileOrBuilder();
}
