// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.profile.grpc;

public interface UpdateRatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.profile.UpdateRatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>float new_rating = 2;</code>
   * @return The newRating.
   */
  float getNewRating();

  /**
   * <code>int32 review_count = 3;</code>
   * @return The reviewCount.
   */
  int getReviewCount();
}
