// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

/**
 * Protobuf type {@code com.hiresphere.booking.Booking}
 */
public final class Booking extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.booking.Booking)
    BookingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Booking.newBuilder() to construct.
  private Booking(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Booking() {
    bookingId_ = "";
    candidateId_ = "";
    interviewerId_ = "";
    slotId_ = "";
    status_ = 0;
    stripePaymentIntent_ = "";
    sessionToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Booking();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_Booking_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_Booking_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.booking.grpc.Booking.class, com.hiresphere.booking.grpc.Booking.Builder.class);
  }

  public static final int BOOKING_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bookingId_ = "";
  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  @java.lang.Override
  public java.lang.String getBookingId() {
    java.lang.Object ref = bookingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookingId_ = s;
      return s;
    }
  }
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBookingIdBytes() {
    java.lang.Object ref = bookingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidateId_ = "";
  /**
   * <code>string candidate_id = 2;</code>
   * @return The candidateId.
   */
  @java.lang.Override
  public java.lang.String getCandidateId() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateId_ = s;
      return s;
    }
  }
  /**
   * <code>string candidate_id = 2;</code>
   * @return The bytes for candidateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateIdBytes() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERVIEWER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object interviewerId_ = "";
  /**
   * <code>string interviewer_id = 3;</code>
   * @return The interviewerId.
   */
  @java.lang.Override
  public java.lang.String getInterviewerId() {
    java.lang.Object ref = interviewerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interviewerId_ = s;
      return s;
    }
  }
  /**
   * <code>string interviewer_id = 3;</code>
   * @return The bytes for interviewerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInterviewerIdBytes() {
    java.lang.Object ref = interviewerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interviewerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLOT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object slotId_ = "";
  /**
   * <code>string slot_id = 4;</code>
   * @return The slotId.
   */
  @java.lang.Override
  public java.lang.String getSlotId() {
    java.lang.Object ref = slotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slotId_ = s;
      return s;
    }
  }
  /**
   * <code>string slot_id = 4;</code>
   * @return The bytes for slotId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSlotIdBytes() {
    java.lang.Object ref = slotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIME_FIELD_NUMBER = 5;
  private long startTime_ = 0L;
  /**
   * <code>int64 start_time = 5;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 6;
  private long endTime_ = 0L;
  /**
   * <code>int64 end_time = 6;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_ = 0;
  /**
   * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
   * @return The status.
   */
  @java.lang.Override public com.hiresphere.booking.grpc.BookingStatus getStatus() {
    com.hiresphere.booking.grpc.BookingStatus result = com.hiresphere.booking.grpc.BookingStatus.forNumber(status_);
    return result == null ? com.hiresphere.booking.grpc.BookingStatus.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_PAID_FIELD_NUMBER = 8;
  private double amountPaid_ = 0D;
  /**
   * <code>double amount_paid = 8;</code>
   * @return The amountPaid.
   */
  @java.lang.Override
  public double getAmountPaid() {
    return amountPaid_;
  }

  public static final int STRIPE_PAYMENT_INTENT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stripePaymentIntent_ = "";
  /**
   * <code>string stripe_payment_intent = 9;</code>
   * @return The stripePaymentIntent.
   */
  @java.lang.Override
  public java.lang.String getStripePaymentIntent() {
    java.lang.Object ref = stripePaymentIntent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stripePaymentIntent_ = s;
      return s;
    }
  }
  /**
   * <code>string stripe_payment_intent = 9;</code>
   * @return The bytes for stripePaymentIntent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStripePaymentIntentBytes() {
    java.lang.Object ref = stripePaymentIntent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stripePaymentIntent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_TOKEN_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionToken_ = "";
  /**
   * <code>string session_token = 10;</code>
   * @return The sessionToken.
   */
  @java.lang.Override
  public java.lang.String getSessionToken() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionToken_ = s;
      return s;
    }
  }
  /**
   * <code>string session_token = 10;</code>
   * @return The bytes for sessionToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionTokenBytes() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 11;
  private long createdAt_ = 0L;
  /**
   * <code>int64 created_at = 11;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookingId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bookingId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, candidateId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interviewerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interviewerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, slotId_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(5, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(6, endTime_);
    }
    if (status_ != com.hiresphere.booking.grpc.BookingStatus.PENDING.getNumber()) {
      output.writeEnum(7, status_);
    }
    if (java.lang.Double.doubleToRawLongBits(amountPaid_) != 0) {
      output.writeDouble(8, amountPaid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stripePaymentIntent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, stripePaymentIntent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, sessionToken_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(11, createdAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookingId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bookingId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, candidateId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interviewerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, interviewerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, slotId_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, endTime_);
    }
    if (status_ != com.hiresphere.booking.grpc.BookingStatus.PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, status_);
    }
    if (java.lang.Double.doubleToRawLongBits(amountPaid_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, amountPaid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stripePaymentIntent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, stripePaymentIntent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, sessionToken_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, createdAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.booking.grpc.Booking)) {
      return super.equals(obj);
    }
    com.hiresphere.booking.grpc.Booking other = (com.hiresphere.booking.grpc.Booking) obj;

    if (!getBookingId()
        .equals(other.getBookingId())) return false;
    if (!getCandidateId()
        .equals(other.getCandidateId())) return false;
    if (!getInterviewerId()
        .equals(other.getInterviewerId())) return false;
    if (!getSlotId()
        .equals(other.getSlotId())) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (status_ != other.status_) return false;
    if (java.lang.Double.doubleToLongBits(getAmountPaid())
        != java.lang.Double.doubleToLongBits(
            other.getAmountPaid())) return false;
    if (!getStripePaymentIntent()
        .equals(other.getStripePaymentIntent())) return false;
    if (!getSessionToken()
        .equals(other.getSessionToken())) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBookingId().hashCode();
    hash = (37 * hash) + CANDIDATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId().hashCode();
    hash = (37 * hash) + INTERVIEWER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInterviewerId().hashCode();
    hash = (37 * hash) + SLOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSlotId().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + AMOUNT_PAID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmountPaid()));
    hash = (37 * hash) + STRIPE_PAYMENT_INTENT_FIELD_NUMBER;
    hash = (53 * hash) + getStripePaymentIntent().hashCode();
    hash = (37 * hash) + SESSION_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSessionToken().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.booking.grpc.Booking parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.booking.grpc.Booking parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.booking.grpc.Booking parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.booking.grpc.Booking parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.booking.grpc.Booking prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hiresphere.booking.Booking}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.booking.Booking)
      com.hiresphere.booking.grpc.BookingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_Booking_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_Booking_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.booking.grpc.Booking.class, com.hiresphere.booking.grpc.Booking.Builder.class);
    }

    // Construct using com.hiresphere.booking.grpc.Booking.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bookingId_ = "";
      candidateId_ = "";
      interviewerId_ = "";
      slotId_ = "";
      startTime_ = 0L;
      endTime_ = 0L;
      status_ = 0;
      amountPaid_ = 0D;
      stripePaymentIntent_ = "";
      sessionToken_ = "";
      createdAt_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_Booking_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.Booking getDefaultInstanceForType() {
      return com.hiresphere.booking.grpc.Booking.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.Booking build() {
      com.hiresphere.booking.grpc.Booking result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.Booking buildPartial() {
      com.hiresphere.booking.grpc.Booking result = new com.hiresphere.booking.grpc.Booking(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hiresphere.booking.grpc.Booking result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bookingId_ = bookingId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.candidateId_ = candidateId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.interviewerId_ = interviewerId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.slotId_ = slotId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.amountPaid_ = amountPaid_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.stripePaymentIntent_ = stripePaymentIntent_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.sessionToken_ = sessionToken_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.createdAt_ = createdAt_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.booking.grpc.Booking) {
        return mergeFrom((com.hiresphere.booking.grpc.Booking)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.booking.grpc.Booking other) {
      if (other == com.hiresphere.booking.grpc.Booking.getDefaultInstance()) return this;
      if (!other.getBookingId().isEmpty()) {
        bookingId_ = other.bookingId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCandidateId().isEmpty()) {
        candidateId_ = other.candidateId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getInterviewerId().isEmpty()) {
        interviewerId_ = other.interviewerId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSlotId().isEmpty()) {
        slotId_ = other.slotId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getAmountPaid() != 0D) {
        setAmountPaid(other.getAmountPaid());
      }
      if (!other.getStripePaymentIntent().isEmpty()) {
        stripePaymentIntent_ = other.stripePaymentIntent_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getSessionToken().isEmpty()) {
        sessionToken_ = other.sessionToken_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bookingId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              candidateId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              interviewerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              slotId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              startTime_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              endTime_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 65: {
              amountPaid_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 74: {
              stripePaymentIntent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              sessionToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              createdAt_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object bookingId_ = "";
    /**
     * <code>string booking_id = 1;</code>
     * @return The bookingId.
     */
    public java.lang.String getBookingId() {
      java.lang.Object ref = bookingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string booking_id = 1;</code>
     * @return The bytes for bookingId.
     */
    public com.google.protobuf.ByteString
        getBookingIdBytes() {
      java.lang.Object ref = bookingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string booking_id = 1;</code>
     * @param value The bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bookingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string booking_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingId() {
      bookingId_ = getDefaultInstance().getBookingId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string booking_id = 1;</code>
     * @param value The bytes for bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bookingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object candidateId_ = "";
    /**
     * <code>string candidate_id = 2;</code>
     * @return The candidateId.
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string candidate_id = 2;</code>
     * @return The bytes for candidateId.
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string candidate_id = 2;</code>
     * @param value The candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidateId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateId() {
      candidateId_ = getDefaultInstance().getCandidateId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_id = 2;</code>
     * @param value The bytes for candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidateId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object interviewerId_ = "";
    /**
     * <code>string interviewer_id = 3;</code>
     * @return The interviewerId.
     */
    public java.lang.String getInterviewerId() {
      java.lang.Object ref = interviewerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interviewerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interviewer_id = 3;</code>
     * @return The bytes for interviewerId.
     */
    public com.google.protobuf.ByteString
        getInterviewerIdBytes() {
      java.lang.Object ref = interviewerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interviewerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interviewer_id = 3;</code>
     * @param value The interviewerId to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      interviewerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string interviewer_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterviewerId() {
      interviewerId_ = getDefaultInstance().getInterviewerId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string interviewer_id = 3;</code>
     * @param value The bytes for interviewerId to set.
     * @return This builder for chaining.
     */
    public Builder setInterviewerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      interviewerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object slotId_ = "";
    /**
     * <code>string slot_id = 4;</code>
     * @return The slotId.
     */
    public java.lang.String getSlotId() {
      java.lang.Object ref = slotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slot_id = 4;</code>
     * @return The bytes for slotId.
     */
    public com.google.protobuf.ByteString
        getSlotIdBytes() {
      java.lang.Object ref = slotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slot_id = 4;</code>
     * @param value The slotId to set.
     * @return This builder for chaining.
     */
    public Builder setSlotId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      slotId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string slot_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlotId() {
      slotId_ = getDefaultInstance().getSlotId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string slot_id = 4;</code>
     * @param value The bytes for slotId to set.
     * @return This builder for chaining.
     */
    public Builder setSlotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      slotId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 start_time = 5;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 start_time = 5;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {

      startTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 end_time = 6;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 end_time = 6;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {

      endTime_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.hiresphere.booking.grpc.BookingStatus getStatus() {
      com.hiresphere.booking.grpc.BookingStatus result = com.hiresphere.booking.grpc.BookingStatus.forNumber(status_);
      return result == null ? com.hiresphere.booking.grpc.BookingStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.hiresphere.booking.grpc.BookingStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000040);
      status_ = 0;
      onChanged();
      return this;
    }

    private double amountPaid_ ;
    /**
     * <code>double amount_paid = 8;</code>
     * @return The amountPaid.
     */
    @java.lang.Override
    public double getAmountPaid() {
      return amountPaid_;
    }
    /**
     * <code>double amount_paid = 8;</code>
     * @param value The amountPaid to set.
     * @return This builder for chaining.
     */
    public Builder setAmountPaid(double value) {

      amountPaid_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double amount_paid = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountPaid() {
      bitField0_ = (bitField0_ & ~0x00000080);
      amountPaid_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object stripePaymentIntent_ = "";
    /**
     * <code>string stripe_payment_intent = 9;</code>
     * @return The stripePaymentIntent.
     */
    public java.lang.String getStripePaymentIntent() {
      java.lang.Object ref = stripePaymentIntent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stripePaymentIntent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stripe_payment_intent = 9;</code>
     * @return The bytes for stripePaymentIntent.
     */
    public com.google.protobuf.ByteString
        getStripePaymentIntentBytes() {
      java.lang.Object ref = stripePaymentIntent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stripePaymentIntent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stripe_payment_intent = 9;</code>
     * @param value The stripePaymentIntent to set.
     * @return This builder for chaining.
     */
    public Builder setStripePaymentIntent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stripePaymentIntent_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string stripe_payment_intent = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStripePaymentIntent() {
      stripePaymentIntent_ = getDefaultInstance().getStripePaymentIntent();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string stripe_payment_intent = 9;</code>
     * @param value The bytes for stripePaymentIntent to set.
     * @return This builder for chaining.
     */
    public Builder setStripePaymentIntentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stripePaymentIntent_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object sessionToken_ = "";
    /**
     * <code>string session_token = 10;</code>
     * @return The sessionToken.
     */
    public java.lang.String getSessionToken() {
      java.lang.Object ref = sessionToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_token = 10;</code>
     * @return The bytes for sessionToken.
     */
    public com.google.protobuf.ByteString
        getSessionTokenBytes() {
      java.lang.Object ref = sessionToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_token = 10;</code>
     * @param value The sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionToken_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string session_token = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionToken() {
      sessionToken_ = getDefaultInstance().getSessionToken();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string session_token = 10;</code>
     * @param value The bytes for sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionToken_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>int64 created_at = 11;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>int64 created_at = 11;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int64 created_at = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000400);
      createdAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.booking.Booking)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.booking.Booking)
  private static final com.hiresphere.booking.grpc.Booking DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.booking.grpc.Booking();
  }

  public static com.hiresphere.booking.grpc.Booking getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Booking>
      PARSER = new com.google.protobuf.AbstractParser<Booking>() {
    @java.lang.Override
    public Booking parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Booking> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Booking> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.booking.grpc.Booking getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

