// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

/**
 * Protobuf enum {@code com.hiresphere.booking.BookingStatus}
 */
public enum BookingStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PENDING = 0;</code>
   */
  PENDING(0),
  /**
   * <code>CONFIRMED = 1;</code>
   */
  CONFIRMED(1),
  /**
   * <code>CANCELLED = 2;</code>
   */
  CANCELLED(2),
  /**
   * <code>COMPLETED = 3;</code>
   */
  COMPLETED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PENDING = 0;</code>
   */
  public static final int PENDING_VALUE = 0;
  /**
   * <code>CONFIRMED = 1;</code>
   */
  public static final int CONFIRMED_VALUE = 1;
  /**
   * <code>CANCELLED = 2;</code>
   */
  public static final int CANCELLED_VALUE = 2;
  /**
   * <code>COMPLETED = 3;</code>
   */
  public static final int COMPLETED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BookingStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BookingStatus forNumber(int value) {
    switch (value) {
      case 0: return PENDING;
      case 1: return CONFIRMED;
      case 2: return CANCELLED;
      case 3: return COMPLETED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BookingStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BookingStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BookingStatus>() {
          public BookingStatus findValueByNumber(int number) {
            return BookingStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hiresphere.booking.grpc.BookingOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final BookingStatus[] VALUES = values();

  public static BookingStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BookingStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.hiresphere.booking.BookingStatus)
}

