// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

public final class BookingOuterClass {
  private BookingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_booking_Booking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_booking_Booking_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_booking_VerifyBookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_booking_VerifyBookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_booking_VerifyBookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_booking_VerifyBookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_booking_GetBookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_booking_GetBookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hiresphere_booking_GetBookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hiresphere_booking_GetBookingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\026com.hiresphere.booking\"" +
      "\230\002\n\007Booking\022\022\n\nbooking_id\030\001 \001(\t\022\024\n\014candi" +
      "date_id\030\002 \001(\t\022\026\n\016interviewer_id\030\003 \001(\t\022\017\n" +
      "\007slot_id\030\004 \001(\t\022\022\n\nstart_time\030\005 \001(\003\022\020\n\010en" +
      "d_time\030\006 \001(\003\0225\n\006status\030\007 \001(\0162%.com.hires" +
      "phere.booking.BookingStatus\022\023\n\013amount_pa" +
      "id\030\010 \001(\001\022\035\n\025stripe_payment_intent\030\t \001(\t\022" +
      "\025\n\rsession_token\030\n \001(\t\022\022\n\ncreated_at\030\013 \001" +
      "(\003\"X\n\024VerifyBookingRequest\022\022\n\nbooking_id" +
      "\030\001 \001(\t\022\024\n\014candidate_id\030\002 \001(\t\022\026\n\016intervie" +
      "wer_id\030\003 \001(\t\"o\n\025VerifyBookingResponse\022\r\n" +
      "\005valid\030\001 \001(\010\0220\n\007booking\030\002 \001(\0132\037.com.hire" +
      "sphere.booking.Booking\022\025\n\rsession_token\030" +
      "\003 \001(\t\"\'\n\021GetBookingRequest\022\022\n\nbooking_id" +
      "\030\001 \001(\t\"U\n\022GetBookingResponse\0220\n\007booking\030" +
      "\001 \001(\0132\037.com.hiresphere.booking.Booking\022\r" +
      "\n\005found\030\002 \001(\010*I\n\rBookingStatus\022\013\n\007PENDIN" +
      "G\020\000\022\r\n\tCONFIRMED\020\001\022\r\n\tCANCELLED\020\002\022\r\n\tCOM" +
      "PLETED\020\0032\343\001\n\016BookingService\022l\n\rVerifyBoo" +
      "king\022,.com.hiresphere.booking.VerifyBook" +
      "ingRequest\032-.com.hiresphere.booking.Veri" +
      "fyBookingResponse\022c\n\nGetBooking\022).com.hi" +
      "resphere.booking.GetBookingRequest\032*.com" +
      ".hiresphere.booking.GetBookingResponseB\037" +
      "\n\033com.hiresphere.booking.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hiresphere_booking_Booking_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hiresphere_booking_Booking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_booking_Booking_descriptor,
        new java.lang.String[] { "BookingId", "CandidateId", "InterviewerId", "SlotId", "StartTime", "EndTime", "Status", "AmountPaid", "StripePaymentIntent", "SessionToken", "CreatedAt", });
    internal_static_com_hiresphere_booking_VerifyBookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hiresphere_booking_VerifyBookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_booking_VerifyBookingRequest_descriptor,
        new java.lang.String[] { "BookingId", "CandidateId", "InterviewerId", });
    internal_static_com_hiresphere_booking_VerifyBookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hiresphere_booking_VerifyBookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_booking_VerifyBookingResponse_descriptor,
        new java.lang.String[] { "Valid", "Booking", "SessionToken", });
    internal_static_com_hiresphere_booking_GetBookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hiresphere_booking_GetBookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_booking_GetBookingRequest_descriptor,
        new java.lang.String[] { "BookingId", });
    internal_static_com_hiresphere_booking_GetBookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hiresphere_booking_GetBookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hiresphere_booking_GetBookingResponse_descriptor,
        new java.lang.String[] { "Booking", "Found", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
