// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

public interface BookingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.booking.Booking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();

  /**
   * <code>string candidate_id = 2;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidate_id = 2;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <code>string interviewer_id = 3;</code>
   * @return The interviewerId.
   */
  java.lang.String getInterviewerId();
  /**
   * <code>string interviewer_id = 3;</code>
   * @return The bytes for interviewerId.
   */
  com.google.protobuf.ByteString
      getInterviewerIdBytes();

  /**
   * <code>string slot_id = 4;</code>
   * @return The slotId.
   */
  java.lang.String getSlotId();
  /**
   * <code>string slot_id = 4;</code>
   * @return The bytes for slotId.
   */
  com.google.protobuf.ByteString
      getSlotIdBytes();

  /**
   * <code>int64 start_time = 5;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 6;</code>
   * @return The endTime.
   */
  long getEndTime();

  /**
   * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.hiresphere.booking.BookingStatus status = 7;</code>
   * @return The status.
   */
  com.hiresphere.booking.grpc.BookingStatus getStatus();

  /**
   * <code>double amount_paid = 8;</code>
   * @return The amountPaid.
   */
  double getAmountPaid();

  /**
   * <code>string stripe_payment_intent = 9;</code>
   * @return The stripePaymentIntent.
   */
  java.lang.String getStripePaymentIntent();
  /**
   * <code>string stripe_payment_intent = 9;</code>
   * @return The bytes for stripePaymentIntent.
   */
  com.google.protobuf.ByteString
      getStripePaymentIntentBytes();

  /**
   * <code>string session_token = 10;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string session_token = 10;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();

  /**
   * <code>int64 created_at = 11;</code>
   * @return The createdAt.
   */
  long getCreatedAt();
}
