// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

/**
 * Protobuf type {@code com.hiresphere.booking.GetBookingResponse}
 */
public final class GetBookingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hiresphere.booking.GetBookingResponse)
    GetBookingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetBookingResponse.newBuilder() to construct.
  private GetBookingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetBookingResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetBookingResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_GetBookingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_GetBookingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hiresphere.booking.grpc.GetBookingResponse.class, com.hiresphere.booking.grpc.GetBookingResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BOOKING_FIELD_NUMBER = 1;
  private com.hiresphere.booking.grpc.Booking booking_;
  /**
   * <code>.com.hiresphere.booking.Booking booking = 1;</code>
   * @return Whether the booking field is set.
   */
  @java.lang.Override
  public boolean hasBooking() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.hiresphere.booking.Booking booking = 1;</code>
   * @return The booking.
   */
  @java.lang.Override
  public com.hiresphere.booking.grpc.Booking getBooking() {
    return booking_ == null ? com.hiresphere.booking.grpc.Booking.getDefaultInstance() : booking_;
  }
  /**
   * <code>.com.hiresphere.booking.Booking booking = 1;</code>
   */
  @java.lang.Override
  public com.hiresphere.booking.grpc.BookingOrBuilder getBookingOrBuilder() {
    return booking_ == null ? com.hiresphere.booking.grpc.Booking.getDefaultInstance() : booking_;
  }

  public static final int FOUND_FIELD_NUMBER = 2;
  private boolean found_ = false;
  /**
   * <code>bool found = 2;</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBooking());
    }
    if (found_ != false) {
      output.writeBool(2, found_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBooking());
    }
    if (found_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, found_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hiresphere.booking.grpc.GetBookingResponse)) {
      return super.equals(obj);
    }
    com.hiresphere.booking.grpc.GetBookingResponse other = (com.hiresphere.booking.grpc.GetBookingResponse) obj;

    if (hasBooking() != other.hasBooking()) return false;
    if (hasBooking()) {
      if (!getBooking()
          .equals(other.getBooking())) return false;
    }
    if (getFound()
        != other.getFound()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBooking()) {
      hash = (37 * hash) + BOOKING_FIELD_NUMBER;
      hash = (53 * hash) + getBooking().hashCode();
    }
    hash = (37 * hash) + FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFound());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hiresphere.booking.grpc.GetBookingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hiresphere.booking.grpc.GetBookingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hiresphere.booking.grpc.GetBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hiresphere.booking.grpc.GetBookingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hiresphere.booking.GetBookingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hiresphere.booking.GetBookingResponse)
      com.hiresphere.booking.grpc.GetBookingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_GetBookingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_GetBookingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hiresphere.booking.grpc.GetBookingResponse.class, com.hiresphere.booking.grpc.GetBookingResponse.Builder.class);
    }

    // Construct using com.hiresphere.booking.grpc.GetBookingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBookingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      booking_ = null;
      if (bookingBuilder_ != null) {
        bookingBuilder_.dispose();
        bookingBuilder_ = null;
      }
      found_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hiresphere.booking.grpc.BookingOuterClass.internal_static_com_hiresphere_booking_GetBookingResponse_descriptor;
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.GetBookingResponse getDefaultInstanceForType() {
      return com.hiresphere.booking.grpc.GetBookingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.GetBookingResponse build() {
      com.hiresphere.booking.grpc.GetBookingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hiresphere.booking.grpc.GetBookingResponse buildPartial() {
      com.hiresphere.booking.grpc.GetBookingResponse result = new com.hiresphere.booking.grpc.GetBookingResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hiresphere.booking.grpc.GetBookingResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.booking_ = bookingBuilder_ == null
            ? booking_
            : bookingBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.found_ = found_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hiresphere.booking.grpc.GetBookingResponse) {
        return mergeFrom((com.hiresphere.booking.grpc.GetBookingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hiresphere.booking.grpc.GetBookingResponse other) {
      if (other == com.hiresphere.booking.grpc.GetBookingResponse.getDefaultInstance()) return this;
      if (other.hasBooking()) {
        mergeBooking(other.getBooking());
      }
      if (other.getFound() != false) {
        setFound(other.getFound());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBookingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              found_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.hiresphere.booking.grpc.Booking booking_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hiresphere.booking.grpc.Booking, com.hiresphere.booking.grpc.Booking.Builder, com.hiresphere.booking.grpc.BookingOrBuilder> bookingBuilder_;
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     * @return Whether the booking field is set.
     */
    public boolean hasBooking() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     * @return The booking.
     */
    public com.hiresphere.booking.grpc.Booking getBooking() {
      if (bookingBuilder_ == null) {
        return booking_ == null ? com.hiresphere.booking.grpc.Booking.getDefaultInstance() : booking_;
      } else {
        return bookingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public Builder setBooking(com.hiresphere.booking.grpc.Booking value) {
      if (bookingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        booking_ = value;
      } else {
        bookingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public Builder setBooking(
        com.hiresphere.booking.grpc.Booking.Builder builderForValue) {
      if (bookingBuilder_ == null) {
        booking_ = builderForValue.build();
      } else {
        bookingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public Builder mergeBooking(com.hiresphere.booking.grpc.Booking value) {
      if (bookingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          booking_ != null &&
          booking_ != com.hiresphere.booking.grpc.Booking.getDefaultInstance()) {
          getBookingBuilder().mergeFrom(value);
        } else {
          booking_ = value;
        }
      } else {
        bookingBuilder_.mergeFrom(value);
      }
      if (booking_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public Builder clearBooking() {
      bitField0_ = (bitField0_ & ~0x00000001);
      booking_ = null;
      if (bookingBuilder_ != null) {
        bookingBuilder_.dispose();
        bookingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public com.hiresphere.booking.grpc.Booking.Builder getBookingBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBookingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    public com.hiresphere.booking.grpc.BookingOrBuilder getBookingOrBuilder() {
      if (bookingBuilder_ != null) {
        return bookingBuilder_.getMessageOrBuilder();
      } else {
        return booking_ == null ?
            com.hiresphere.booking.grpc.Booking.getDefaultInstance() : booking_;
      }
    }
    /**
     * <code>.com.hiresphere.booking.Booking booking = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hiresphere.booking.grpc.Booking, com.hiresphere.booking.grpc.Booking.Builder, com.hiresphere.booking.grpc.BookingOrBuilder> 
        getBookingFieldBuilder() {
      if (bookingBuilder_ == null) {
        bookingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hiresphere.booking.grpc.Booking, com.hiresphere.booking.grpc.Booking.Builder, com.hiresphere.booking.grpc.BookingOrBuilder>(
                getBooking(),
                getParentForChildren(),
                isClean());
        booking_ = null;
      }
      return bookingBuilder_;
    }

    private boolean found_ ;
    /**
     * <code>bool found = 2;</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return found_;
    }
    /**
     * <code>bool found = 2;</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {

      found_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool found = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      found_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hiresphere.booking.GetBookingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.hiresphere.booking.GetBookingResponse)
  private static final com.hiresphere.booking.grpc.GetBookingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hiresphere.booking.grpc.GetBookingResponse();
  }

  public static com.hiresphere.booking.grpc.GetBookingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBookingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetBookingResponse>() {
    @java.lang.Override
    public GetBookingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBookingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBookingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hiresphere.booking.grpc.GetBookingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

