// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

public interface VerifyBookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.booking.VerifyBookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();

  /**
   * <code>string candidate_id = 2;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidate_id = 2;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <code>string interviewer_id = 3;</code>
   * @return The interviewerId.
   */
  java.lang.String getInterviewerId();
  /**
   * <code>string interviewer_id = 3;</code>
   * @return The bytes for interviewerId.
   */
  com.google.protobuf.ByteString
      getInterviewerIdBytes();
}
