// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

// Protobuf Java Version: 3.25.3
package com.hiresphere.booking.grpc;

public interface VerifyBookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hiresphere.booking.VerifyBookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>.com.hiresphere.booking.Booking booking = 2;</code>
   * @return Whether the booking field is set.
   */
  boolean hasBooking();
  /**
   * <code>.com.hiresphere.booking.Booking booking = 2;</code>
   * @return The booking.
   */
  com.hiresphere.booking.grpc.Booking getBooking();
  /**
   * <code>.com.hiresphere.booking.Booking booking = 2;</code>
   */
  com.hiresphere.booking.grpc.BookingOrBuilder getBookingOrBuilder();

  /**
   * <code>string session_token = 3;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string session_token = 3;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
